### ISSUE TITLE
Documentation Work: How routing is bootstrapped

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#129]
## Task Description
Write, review, and post a How routing is bootstrapped section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
This content should:
- Document how routing is bootstrapped for the Forms Library 
- Include code examples.
- [Research on routing - Micah's Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2002354239/Current+Forms+Library+Routing+Research)
- [Routing information that Chris wrote for Formulate - for background information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2021-05-18-forms-library.md#route-component) / [Confluence page version](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2025029667/Forms+Library+Design+Document+WIP)
- Highlight the limitations of how routing current works. For example, a big gotcha is that `/introduction` has to live at the index route of an application, if it's a form application. 

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How routing is bootstrapped draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] How routing is bootstrapped content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2132738187/Forms+Library+-+How+routing+is+generated+DRAFT)
- [x] How routing is bootstrapped content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2132738187/VA+Forms+Library+-+How+routing+is+generated)

**Comment by micahchiang** [comment]
Draft is up - https://vfs.atlassian.net/wiki/spaces/PWD/pages/2132738187/Forms+Library+-+How+routing+is+generated+DRAFT

**Comment by bjmccotter7192** [comment]
LGTM! Nice work @micahchiang
