### ISSUE TITLE
Field: Radio group

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va-forms-system-core#13]
## Description
Should have the same look as already established on [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-radio--default). Work is to wrap the radio group in the Formik wrapper, not change anything with the look and feel.

<details><summary>Storybook Radio group UI</summary>

![Screen Shot 2022-03-25 at 10.39.29 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/6f1fca81-c5f5-4d2c-801c-276b45c954d7)
![Screen Shot 2022-03-25 at 10.39.50 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/e32a788f-07e1-4a49-9746-a4f314e48849)
![Screen Shot 2022-03-25 at 10.40.02 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/86eaee47-23fb-4936-b051-8b809b14ea67)
</details>

## Considerations
- [va-forms-system-core TextField](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/5aad5bf6ecd1db653fae60f9c3b337d7258da892/src/form-builder/TextField.tsx#L8) as a reference
- [va-forms-system-core TextField unit tests](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/b95fb7fb5b792a57fc52075a9ab3230e8b6282d5/test/form-builder/CheckboxField.test.tsx#L0-L1)
- Radio group will also be used for YesNo Widget.

## Tasks
- [x] Import the [va-radio](https://design.va.gov/storybook/?path=/docs/components-va-radio--default) and wrap it with formik
- [x] Write tests for the new radio group field
- [x] Include code block declarations for automatic documentation generation

## Acceptance Criteria
- [ ] Above tasks have been complete
- [ ] PR has been merged into main

**Comment by taylorkaren** [comment]
PR: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/264.

**Comment by taylorkaren** [comment]
PR: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/267.
