### ISSUE TITLE
Documentation Work: How to bypass schemaForm

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#130]
## Task Description
Write, review, and post a How to bypass schemaForm section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
 - [spreadsheet for doc migration](https://docs.google.com/spreadsheets/d/1V7T8iTBFNFB96WDzidavryxCuxgYe56EDjTuPVIXscE/edit#gid=0)
- [Bypassing the SchemaForm on the current help site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/bypassing-schemaform/)
- Most likely a direct copy paste job, as this is as up to date as it can be. Recommend running through the existing guide, identifying gaps or errors, and augmenting the material as necessary.
 - From Brooks comment on ticket 160: There is also this: https://department-of-veterans-affairs.github.io/formulate/how-to-guides/how-to-integrate-with-old-forms.html. - NOT NEEDED. THIS IS FOCUSED ON USING FORMULATE/VA FORMS SYSTEM CORE AND OUR HELP UPDATES SHOULD ONLY COVER THE CURRENT FORMS LIBRARY.

This content should:
 - Document how to truly eject out of schema/uiSchema.
- Be reviewed and updated as needed when moving to the new site. Spreadsheet says it is up to date, so there may be minimal work here.

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How to bypass schemaForm draft content has been written: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2138177682/VA+Forms+Library-+Bypassing+the+Schema+Form
- [ ] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [ ] Feedback has been addressed.
- [x] How to bypass schemaForm content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980).
- [ ] How to bypass schemaForm content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html).

**Comment by mlauren** [comment]
updated link since formulate is now va-forms-system-core: https://department-of-veterans-affairs.github.io/va-forms-system-core/how-to-guides/how-to-integrate-with-old-forms.html

**Comment by bjmccotter7192** [comment]
Left a brief comment but well done and looks great!
