### ISSUE TITLE
Documentation Work: How to set up Save in Progress

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#131]
## Task Description
Write, review, and post a How to set up Save in Progress section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
 - [spreadsheet for doc migration](https://docs.google.com/spreadsheets/d/1V7T8iTBFNFB96WDzidavryxCuxgYe56EDjTuPVIXscE/edit#gid=0)
- Current guide is pretty solid, can most likely do a direct lift
- [Setting up Save in Progress on the current help site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/save-in-progress/): move to the new site.
- **Note** it's possible that prefill needs to be configured in vets-api for SiP to work. Confirming this and will update this point once I know more. If this is the case, then part of this guide should link to the that gets created for #132 

This content should:
- Be reviewed and updated as needed when moving to the new site.
- **Note: This doesn't include prefill (#132) which is different but may have some crossover implications.**

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How to set up Save in Progress draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] How to set up Save in Progress content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2114453614/VA+Forms+System+-+How+to+set+up+Save+In+Progress+SiP+DRAFT)
- [x] How to set up Save in Progress content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---How-to-set-up-Save-In-Progress-(SiP).2114453614.html)

**Comment by micahchiang** [comment]
**NOTE**: There is a section on the [current SiP documentation page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/save-in-progress) about setting up widgets for static pages. This isn't part of setting up SiP. A separate ticket should be made to migrate this content over separately in its own how-to guide.

**Comment by micahchiang** [comment]
Page in Platform Draft Space - https://vfs.atlassian.net/wiki/spaces/PWD/pages/2114453614/VA+Forms+System+-+How+to+set+up+Save+In+Progress+SiP+DRAFT
