### ISSUE TITLE
Documentation Work: How to set up Pre-fill

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#132]
## Task Description
Write, review, and post a How to set up Pre-fill section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
This content should:
- Document how to set up prefill (this guide requires work in vets-api)
- Include code examples.
- [Example PR of configuring prefill for a form](https://github.com/department-of-veterans-affairs/vets-api/pull/5391/files)

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How to set up Pre-fill draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
- [x] Feedback has been addressed.
- [x] How to set up Pre-fill content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2115534942/VA+Forms+System+-+Working+With+Pre-Fill). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2115534942/VA+Forms+System+-+Working+With+Pre-Fill)
- [x] How to set up Pre-fill content has been posted to the [VA Platform Documentation - Forms Lilbrary Working with Pre-Fill](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2115534942/VA+Forms+System+-+Working+With+Pre-Fill).

**Comment by micahchiang** [comment]
LGTM! Nice job @bjmccotter7192
