### ISSUE TITLE
Documentation Work: How to hide pages and chapters in a form

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#133]
## Task Description
Write, review, and post a How to hide pages and chapters in a form section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
- [Conditionally including a page help on the current site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/common-patterns-for-building-forms/#conditionally-including-a-page)
- [Conditional pages help on the current site - scroll down](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/form-tutorial-intermediate/)
- [686c-674](https://github.com/department-of-veterans-affairs/vets-website/blob/da8dd6bcaae02605ff53dcd89aabaf18748181f4/src/applications/disability-benefits/686c-674/config/form.js#L141) Conditionally hides entire chapters, consider referencing it in the how to guide

This content should:
- Document how to hide pages and entire chapters in a form 
- Include code examples.

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How to hide pages and chapters in a form draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Micah
    - [x] Susanna
    - [x] Nick
    - [x] Lauren
- [x] Feedback has been addressed.
- [x] How to hide pages and chapters in a form content has been posted to the [Forms Library - How to hide pages and chapters in a form PWD](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2128806034/Forms+Library+-+How+to+hide+pages+and+chapters+in+a+form).
- [ ] How to hide pages and chapters in a form content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2128806034/VA+Forms+Library+-+How+to+hide+pages+and+chapters+in+a+form)

**Comment by micahchiang** [comment]
[The getting started](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2104197265/VA+Forms+System+-+Getting+Started+with+VAFS) doc already has a section on this so hopefully not too much additional work needs to be done. We may be able to just split the appropriate content out into its own page.

**Comment by micahchiang** [comment]
LGTM! Loved the live video examples.

**Comment by nickjg231** [comment]
Looks good -- The videos were very helpful for me, but I do have a question. In your first [`Conditionally Hide Chapter` example](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2128806034/VA+Forms+Library+-+How+to+hide+pages+and+chapters+in+a+form#Conditionally-Hide-Chapter), is it necessary that the chapter _and_ its two pages have the `depends` property, or would it still have the same functionality if the `depends` property were removed from those child pages and remain on just the chapter itself?

**Comment by bjmccotter7192** [comment]
That's a good question, so after testing a little, looks like you have to have the chapter and the page to toggle the whole chapter. When just placing the depends on the chapter and not the page, the page still shows up. If you have a chapter with 1 page and you place the depends on the page, then the chapter will disappear.
