### ISSUE TITLE
Documentation Work: How to create custom fields and widgets for use in uiSchema

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#134]
## Task Description
Write, review, and post a How to create custom fields and widgets for use in uiSchema section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
 - [spreadsheet for doc migration](https://docs.google.com/spreadsheets/d/1V7T8iTBFNFB96WDzidavryxCuxgYe56EDjTuPVIXscE/edit#gid=0)
- [Creating custom fields and widgets content on the current help site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/creating-custom-fields-and-widgets/): rewrite this content (see list below for what content should include) and move to the new site.

This content should:
- Document the "what" and the "how."
- Document how to properly build custom widgets.

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How to create custom fields and widgets for use in uiSchema content has been written. (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2115567784/VA+Forms+System+-+Creating+custom+fields+and+widgets)
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] How to create custom fields and widgets for use in uiSchema content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2115567784/VA+Forms+System+-+Creating+custom+fields+and+widgets)
- [x] How to create custom fields and widgets for use in uiSchema content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2115567784/VA+Forms+Library+-+Creating+custom+fields+and+widgets)

**Comment by harshil1793** [comment]
Page in PWD Space:
https://vfs.atlassian.net/wiki/spaces/PWD/pages/2115567784/VA+Forms+System+-+Creating+custom+fields+and+widgets

**Comment by micahchiang** [comment]
Looks good @harshil1793! I think it'd be really beneficial to include just a brief walkthrough of actually creating a custom widget i.e. a simple react component that plugs into `ui:widget`with a screenshot of it rendered in the browser.
