### ISSUE TITLE
Documentation Work: How to use updateSchema and replaceSchema

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#135]
## Task Description
Write, review, and post a How to use updateSchema and replaceSchema section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
This content should:
- Document how to use `updateSchema` to modify a field’s original schema properties.
- Document how to use `replaceSchema` to replace a field's original schema. 
- Include code examples.
- [root helper function in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/8e6a303b320af87c4d8c4f577a43f39b4ecac4bc/src/platform/forms-system/src/js/state/helpers.js#L256)

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How to use updateSchema and replaceSchema draft content has been written. (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2121072697/VA+Forms+System+-+How+to+use+updateSchema+and+replaceSchema+DRAFT)
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Micah
- [x] Feedback has been addressed.
- [x] How to use updateSchema and replaceSchema content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980).
- [x] How to use updateSchema and replaceSchema content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html).

**Comment by micahchiang** [comment]
Confluence page here - https://vfs.atlassian.net/wiki/spaces/PWD/pages/2121072697/VA+Forms+System+-+How+to+use+updateSchema+and+replaceSchema+DRAFT

**Comment by bjmccotter7192** [comment]
Nice work I feel like I just learned a ton myself with this!
