### ISSUE TITLE
(Karen Draft/Micah to review) Documentation Work: How to use replaceSchema

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#136]
**NOTE** Format of this content should be similar to the format for How to use updateSchema (#135). Could be good to have the same person work on both tickets.

## Task Description
Write, review, and post a How to use replaceSchema section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
This content should:
- Document how to use replaceSchema to modify a field’s original schema properties.
- Include code examples.
- **_Anything else?_**

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [ ] How to use replaceSchema content has been written.
- [ ] An FLT member has reviewed and provided feedback on the draft content.
- [ ] Feedback has been addressed.
- [ ] How to use replaceSchema content has completed the VA review and approval process (if applicable).
- [ ] How to use replaceSchema content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html).

**Comment by micahchiang** [comment]
After looking at the source code for replaceSchema, I think this ticket can be closed and merged into the one about updateSchema
