### ISSUE TITLE
Documentation Work: How to use the Save in Progress menu for faster development

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#137]
_**NOTE: This is functionality available on local dev and staging only. It pre-fills data up to a certain page in the page flow to facilitate developer testing - it is NOT the function that pre-fills data on a form for an end user (that is ticket #132).**_

## Task Description
Write, review, and post a How to use the Save in Progress menu for faster development section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
 - [spreadsheet for doc migration](https://docs.google.com/spreadsheets/d/1V7T8iTBFNFB96WDzidavryxCuxgYe56EDjTuPVIXscE/edit#gid=0)
- [Using the Save in Progress menu on the current help site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/save-in-progress-menu/)
- This is most likely a direct copy and paste job, but recommend running through the tutorial to make sure you can achieve what the guide says you should be able to do.

This content should:
- Show developers how to use formData for local development so they don't have to manually fill out forms to test changes.
- Be reviewed and updated as needed when moving to the new site.

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How to use the Save in Progress menu for faster development draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Lauren
    - [x] Nick
    - [x] Micah
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] How to use the Save in Progress menu for faster development content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2133164071/VA+Forms+System+-+How+to+use+the+Save+in+Progress+menu+for+faster+development)
- [x] How to use the Save in Progress menu for faster development content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2133164071/VA+Forms+Library+-+How+to+use+the+Save+in+Progress+menu+for+faster+development)

**Comment by bjmccotter7192** [comment]
LGTM!
