### ISSUE TITLE
(ALSO UPDATE PROD GETTING STARTED PAGE) Documentation Work: How to validate field data based on values from another field

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#138]
_**WHEN THIS TICKET MOVES TO PROD, WE ALSO NEED TO UPDATE THE GETTING STARTED PAGE (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2104197265/VA+Forms+Library+-+Getting+Started+with+the+Forms+Library) TO REMOVE THE CONTENT ON THAT PAGE THIS IS NOW INCLUDED ON THIS PAGE AND INSTEAD LINK TO THIS PAGE.**_

## Task Description
Write, review, and post a How to validate field data based on values from another field section on the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html) as defined and described on the  [Proposed Information Architecture for Forms Library documentation on platform website Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website).

## Considerations
- [Validating a field based on other fields in the same object](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/common-patterns-for-building-forms/#validating-a-field-based-on-other-fields-in-the-same-object)
- [28-8832 form in production as example](https://github.com/department-of-veterans-affairs/vets-website/blob/5e7c79ebf3e03c5c9d4b9d96f77f515699b5c811/src/applications/vre/28-8832/config/chapters/claimant-information/claimantAddress.js#L39-L61)

This content should:
- Be reviewed and updated as needed when moving to the new site.

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] How to validate field data based on values from another field draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] How to validate field data based on values from another field content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2139062445/VA+Forms+Library+-+Validating+a+field+based+on+values+from+another+field)
- [x] How to validate field data based on values from another field content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2139062445/VA+Forms+Library+-+Validating+a+field+based+on+values+from+another+field)
- [x] Getting Started page has been updated in the Developer Docs staging area to replace the content on that page that is now included on this page with a link to this new page.

**Comment by micahchiang** [comment]
Looks like @bjmccotter7192 has included a section on this in the [getting started document](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2104197265/VA+Forms+System+-+Getting+Started+with+VAFS). It may be worth taking what's there and splitting it into its own page.

**Comment by harshil1793** [comment]
@micahchiang As I am creating this new page, are we planning to delete from [getting started document](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2104197265/VA+Forms+System+-+Getting+Started+with+VAFS) as part of this story?

**Comment by micahchiang** [comment]
@harshil1793 - Let's keep it on the getting started page for now as well. We can think about refining the getting started page section about validation and linking to your page a little bit down the road.

**Comment by harshil1793** [comment]
Sounds good. I'll try to give different example then in getting started page.

**Comment by harshil1793** [comment]
Ready for review in PWD space: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2139062445/VA+Forms+Library+-+Validating+a+field+based+on+values+from+another+field

**Comment by bjmccotter7192** [comment]
LGTM
