### ISSUE TITLE
Documentation Work: How to conditionally make fields required

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#142]
## Description
In `uiSchema` there's an option called `ui:required`. This property accepts a function that includes formData and some other arguments, with which a field can be optionally made required. This is beneficial because sometimes fields need to be included in a schema but their requirement is dependent on values from other parts of the formData. A How-to guide should be written that covers how to achieve this. 

## Considerations
- [current documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/about-the-schema-and-uischema-objects) - do a search for ui:required to jump to the specific piece
- [basic example in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/e36bda84f07afd5e4167d080328191f54862c3bc/src/applications/ask-a-question/form/contactInformation/contactInformationPage.js#L36)
- [example where index is used to drill down into array data](https://github.com/department-of-veterans-affairs/vets-website/blob/1ab4f90c883ef89f0199bcbd6a5ef274ff22fb7c/src/platform/forms-system/src/js/definitions/profileAddress.js#L222)
- Mention of `ui:required` in ticket #120 could potentially link to this how-to guide
- Should live in the "How-to Guides" section of [proposed IA](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website)

## Tasks
- Write a how to guide that covers basic and more in-depth examples of how ui:required is currently used in vets-website

## Acceptance Criteria
- [x] How to conditionally make fields required draft content has been written. (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2122285213/VA+Forms+System+-+How+to+conditionally+make+fields+required)
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
    - [x] Nick
    - [x] Lauren
- [x] Feedback has been addressed.
- [x] How to conditionally make fields required content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980).
- [x] How to conditionally make fields required content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2142339090/VA+Forms+Library+-+How+to+conditionally+make+fields+required)

**Comment by micahchiang** [comment]
I think @bjmccotter7192 already has a section for this on the [getting started document](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2104197265/VA+Forms+System+-+Getting+Started+with+VAFS#Conditional-required-fields). We could probably take what's there and put it into a separate how-to guide.

**Comment by kkomes** [comment]
I plan to put more detail into this one.

**Comment by micahchiang** [comment]
LGTM! Thanks Komes!

**Comment by bjmccotter7192** [comment]
LGTM! Left one comment but otherwise well done.
