### ISSUE TITLE
Documentation Work: How to include view-only data

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#143]
## Description
Sometimes forms do not want to ask for things like biographical data, instead choosing to display things VA already has on file such as name, dob, gender, etc. In this instance, one approach is to include a react component that hooks into the redux store and pulls information from profile.

## Considerations
- [Example in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/d32b1096f0bb9b787767d4a2ded33efd7f2a99de/src/applications/disability-benefits/686c-674/config/chapters/veteran-information/veteran-information/VeteranInformationComponent.js#L1)
- [Current documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/common-patterns-for-building-forms#creating-a-block-of-text-with-no-associated-fields)
- Mention the necessity for a schema that has properties set to an empty object. 
- Mention properties that use the `view:` prefix and reference the how to guide that covers `view:` properties. 

## Tasks
- Create a how to guide that lives in the "how to guide" section of the [proposed IA page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website) for form documentation

## Acceptance Criteria
- [x] How to include view-only data draft content has been written. (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2109407531/VA+Forms+System+-+How+to+include+view-only+data)
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
- [x] Feedback has been addressed.
- [x] How to include view-only data content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980).
- [x] How to include view-only data content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---How-to-include-view-only-data.2109407531.html)

**Comment by micahchiang** [comment]
LGTM! Nice work @kkomes
