### ISSUE TITLE
Documentation Work: How to work with transformForSubmit

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#144]
## Description
`transformForSubmit` is an optional [top level property on the formConfig object](https://github.com/department-of-veterans-affairs/vets-website/blob/9e2b1d6522a568d5b23c72b95d7101345c969f0a/src/applications/disability-benefits/996/config/form.js#L90). If no custom `transformForSubmit` function is provided, then the [default transformForSubmit](https://github.com/department-of-veterans-affairs/vets-website/blob/a94ba75c0deee25f297e3a20a9f16b6a7e7f128f/src/platform/forms-system/src/js/helpers.js#L638) is run. 

`transformForSubmit` functions are useful if data needs to be reshaped or adapted before being sent to the backend. 

## Considerations 
- [custom transformForSubmit example](https://github.com/department-of-veterans-affairs/vets-website/blob/d4529630dd999c8ff9679c0f3eb789bb434265f2/src/applications/appeals/10182/config/form.js#L80)
- [view:fields example](https://github.com/department-of-veterans-affairs/vets-website/blob/f285cc7ad7b1b473c82da1916aa10b3f9c8aec56/src/applications/appeals/10182/pages/evidenceIntro.js#L11)

## Tasks
- Create a how-to guide that lives in [proposed IA page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website) in confluence.

## Acceptance Criteria
- [x] How to work with transformForSubmit draft content has been written. (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2110259265/VA+Forms+System+-+How+to+work+with+transformForSubmit)
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
    - [x] Nick
    - [x] Lauren
- [x] Feedback has been addressed.
- [x] How to work with transformForSubmit content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980).
- [x] How to work with transformForSubmit content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2142339073/VA+Forms+Library+-+How+to+work+with+transformForSubmit)
