### ISSUE TITLE
Documentation Work: How to use ReviewCardField

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#145]
## Description 
[Current documentation page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/using-available-fields/)

The original intent of this page isn't clear, but as of right now there is only one example for a specific field, the [ReviewCardField](https://github.com/department-of-veterans-affairs/vets-website/blob/25e17c6aaf98287bddac051ba2a8722fe60dd181/src/platform/forms-system/src/js/components/ReviewCardField.jsx#L1). This should be migrated and converted into a how to guide specifically for `ReviewCardField`. 

## Considerations
- [ReviewCardField component](https://github.com/department-of-veterans-affairs/vets-website/blob/25e17c6aaf98287bddac051ba2a8722fe60dd181/src/platform/forms-system/src/js/components/ReviewCardField.jsx#L1)
- [Current documentation - Using available fields](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/using-available-fields/)
- Include screen caps, images, gifs, etc if possible

## Tasks
- Create a how to guide that lives in the how to guide section of the [proposed IA page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2080374892/Proposed+Information+Architecture+for+Forms+Library+documentation+on+platform+website) in confluence

## Acceptance Criteria
- [x] How to use ReviewCardField draft content has been written.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] How to use ReviewCardField content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2149154972/VA+Forms+Library+-+How+to+use+the+ReviewCardField)
- [x] How to use ReviewCardField content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2149154972/VA+Forms+Library+-+How+to+use+the+ReviewCardField)

**Comment by micahchiang** [comment]
Looks good, thanks @harshil1793!
