### ISSUE TITLE
Q2 Research: Mobile Device Support Baseline

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#147]
## Task Description
- Look into any existing research around forms usage on mobile devices.
- Look at Google Analytics for mobile usage info; e.g., % of total traffic, % of forms page traffic, what are the top devices and OS versions?
- Write up findings for the first two bullet points on a Confluence page.

## Acceptance Criteria
- [x] Draft content has been written.
- [x] FLT members have reviewed and provided feedback on [the draft content:](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2192703646/VA+Forms+Mobile+Device+Analytics)
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Kavitha
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [x] Feedback has been addressed.

## Considerations
- Goal is to set a support baseline for forms on mobile devices
- Findings for bullet point #2 will be used to update the Mobile Device table on the [VAFSC Browser and Device Support Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2193064098/VA+Forms+System+Core+VAFSC+Browser+and+Device+Support). - KT Done, 5/12/22.
- Note from Karen to Karen: Include insights from this research on a Team of Teams slide. - DONE, 5/17/22.

**Comment by bjmccotter7192** [comment]
LGTM!

**Comment by micahchiang** [comment]
LGTM, great work @biannuz!
