### ISSUE TITLE
Technology Stand Up

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#150]
## Task Description
Stand up the basic technical infrastructure needed to support moving forward with Formulate as the basis for the new VA Forms System Core.
- [x] Rename the existing [Formulate repo](https://github.com/department-of-veterans-affairs/formulate) to VA Forms System Core.
- [x] Update the [repo readme](https://github.com/department-of-veterans-affairs/formulate#readme) to reflect the new name of the repo and the work that will be done in this repo.
- [x] Update the repo About section to make it clear that this repo is for new Forms System Core work, it is not something currently in use.
- [x] Address downstream implications of renaming the repository:
    - [x] npm publishing (Formulate is in a branch, not in production, have to manually publish)
    - [x] vets-website dependency

## This is done when...
- [ ] All items in the Task Description section are checked off as having been completed.

**Comment by taylorkaren** [comment]
Use the existing Formulate repo.
Rename it to something less ambiguous - VA Forms System? 
Market as a new Forms System, distinguish it from the current Forms Library, rename the documentation we've been working on to Forms Library?

From ticket 76:
Rename the repository itself from formulate to...
Update the readme so it contains any new information
Update the About section to make it clear that this repo is for new Forms Library work, it is not something currently in use.
Renaming the repository itself may have downstream implications: npm publishing, vets-website dependency etc. Will need to weigh whether or not a rename is worth the effort here.

**Comment by bjmccotter7192** [comment]
Hey All, I have created a draft PR here: [LInk to PR](https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/181).
