### ISSUE TITLE
Communicate the new Forms Library Help Docs Location

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#159]
## Task Description
* Communicate the new Forms Library Help Docs Location - see this Confluence page for details:
https://vfs.atlassian.net/wiki/spaces/FLT/pages/2111111211/Communicating+the+new+Forms+Library+Documentation+Location

## Acceptance Criteria
The new location for Forms Library documentation (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System-Overview.2085355587.html) has been communicated via the following:
- [x] #vfs-all-teams Slack channel
- [x] Cross-post announcement to the #platform-design-system Slack channel
- [x] Cross-post announcement to the #pst-forms-library Slack channel
- [x] Cross-post announcement to the #vfs-engineers Slack channel
- [x] Cross-post announcement to the #vfs-frontend Slack channel
- [x] Cross-post announcement to the #design Slack channel
- [x] Cross-post announcement to the #vsa-product Slack channel (instead of announcing at a VSA Demo meeting, as  demos are on hold for now (between contract periods).

**Comment by taylorkaren** [comment]
This message was posted to the Slack channels listed in the ticket description:

:mega: Announcement :mega:

Updated Forms Library documentation is now available on the Platform website!

If you are a Forms Library user:
- Please bookmark the VA Forms Library Overview page for easy access to all Forms Library help content.
- This is now the definitive location for all Forms Library documentation; please remove any bookmarks you may have to other Forms Library documentation, as the Forms Library Team will be deprecating old Forms Library documentation over the next few weeks.
- If you don’t find what you need, please submit a documentation request to the Forms Library Team via the #vfs-platform-support Slack channel.
