### ISSUE TITLE
Retire old Formulate boards?

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#161]
## Task Description
- After the tickets on the old [Form routing board](https://github.com/department-of-veterans-affairs/va-forms-system-core/projects/2) and old [Form builder board](https://github.com/department-of-veterans-affairs/va-forms-system-core/projects/1) have been reviewed (on tickets #168 and #169, respectively), decide if we need to keep these boards and their related projects.

## This task is done when
- [x] Decision is made on keeping the old Form Routing and Form Builder projects.
    - [ ] If yes, TBD.
    - [x] If no, close the projects (https://github.com/department-of-veterans-affairs/va-forms-system-core/projects)
