### ISSUE TITLE
Documentation Work: Using Form Widgets and Fields - Review Comments

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#165]
## Task Description
Use this ticket to log review comments on the [Using Form Widgets and Fields page](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2089812076/VA+Forms+System+-+Using+Form+Widgets+and+Fields+Draft) (written via work on ticket #127) that will take additional time to address.
**Note, this page is now published on the depo platform and should be modified there.**

## Add List Here
- [x] Add screenshots for more complex widgets
- [x] Re: Micah, mentioning where they get bundled in is valuable, and should be included in a follow up ticket. Information that will be helpful for the follow up ticket: Widgets that get bundled into the SchemaForm component and passed to RJSF https://github.com/department-of-veterans-affairs/vets-website/blob/150a9867939b011ab385b908fa54cae67dd12ec0/src/platform/forms-system/src/js/widgets/index.js#L1
Widgets bundled directly in the react-jsonschema-form repo
https://github.com/department-of-veterans-affairs/react-jsonschema-form/blob/master/src/components/Form.js#L116
- [x] Add example for SSN widget
- [x] At "See usage of custom field creation." link to doc on custom field creation
- [x] Any code cleanup, i.e., sometimes the chapter and page is included and sometimes just uiSchema and schema, this is understandable but could be more consistent, which would be easier for those new to the form system

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## This is done when...
- [x] The comments in the Add List Here section have been completed.
- [x] FLT members have reviewed and provided feedback on the updated content:
     - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] Updated page has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980). (https://vfs.atlassian.net/wiki/spaces/PWD/pages/2089812076/VA+Forms+System+-+Using+Form+Widgets+and+Fields+Draft)
- [x] Updated page has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://vfs.atlassian.net/wiki/spaces/pilot/pages/2089812076/VA+Forms+Library+-+Using+Form+Widgets+and+Fields)

**Comment by bjmccotter7192** [comment]
Well done, i really like all the videos and images that correspond with the code snippets directly.

**Comment by micahchiang** [comment]
Great job @sdk-irl!

**Comment by mlauren** [comment]
This is really good! helped a lot as a new person
