### ISSUE TITLE
Identify remaining Formulate fields and widgets that should be built

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#169]
## Description
While progress on Formulate has been made, there may still be some outstanding fields that need to be added to the library. This ticket should analyze the remaining fields and widgets necessary for building forms effectively with the library. 

## Considerations
- [Existing form fields available](https://github.com/department-of-veterans-affairs/formulate/tree/master/src/form-builder)
- All fields should import and use appropriate design system web components
- [Design System Component Documentation](https://design.va.gov/storybook/?path=/story/about-introduction--page)
    - Actively maintained components are prefixed by `va-` and may include components useable inside formulate
- Other commonly used fields or widgets that aren't present in Storybook should be composed with base components. For example, if we wanted to include an SSN component, because there is no `va-ssn` web component, we could instead build our own using the `va-text-input` component as the base component, as it has existing react bindings. 
- Review the existing [Formulate Form builder tickets](https://github.com/department-of-veterans-affairs/va-forms-system-core/projects/1)
    - Look at the open ones, figure out which of those we should bring over to our board, and move them.
    - Look at the closed ones, figure out if any of the work on those tickets will need to be redone or can be used as 

## Tasks
- [x] Compile a list of the fields already built in Formulate **and** the most commonly used fields and widgets not already built in Formulate so that we have a master list of fields and widgets for the first iteration of the VA Forms System Core. This will be used for ticket #167.
- [x] Stub out tickets for each of the items not already built in Formulate so they can be groomed during backlog refinement

## Acceptance Criteria
- [x] Field and Widgets list has been compiled on a page in the FLT Confluence space in the Forms System Core Architecture section.
- [x] Tickets have been stubbed out for each field and widget that still needs to be built.

**Comment by bjmccotter7192** [comment]
# VAFSC Fields & Widgets

## Already Created
- CheckboxField (*Implemented with va-checkbox*)
- DateField (**NOTE:** Implemented with Simple Date "Non" web component)
- SelectField (*Implemented with va-select*)
- TextField (*Implemented with va-text-input*)

## Web Components Not Added
- va-accordion
- va-breadcrumbs
- va-checkbox-group
- va-loading-indicator
- va-pagination
- va-radio
- va-telephone
- va-table (DO NOT USE YET)
- va-process-list (Introduction Page?)

## Design System Tickets
- Field: Text Area
- Field: Radio Group
- Field: File Input
- Form Builder: List Loop

## Commonly Used Fields/Components/Widgets
- CurrentOrPastDate
- DateRange
- Email
- File
- FullName
- Phone
- SSN
- Address
- FullName
- YesNoWidget

**Possibles**
- FormTitle
- SchemaForm
- ArrayField
- FormFooter
- ServicePeriodView

## Other Web Components
- va-additional-info
- va-alert
- va-banner
- va-featured-content
- va-modal
- va-on-this-page
- va-progress-bar
- va-promo-banner
- va-segmented-process-bar

**Comment by bjmccotter7192** [comment]
[Confluence Document with Proposed Components](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2140274719/VAFSC+Needed+Components+Web+Components)

**Comment by bjmccotter7192** [comment]
I have created a bunch of tickets in the unrefined, I would like to discuss some of the other fields/components/widgets on the document above and see what other tickets we think we should create.

**Comment by taylorkaren** [comment]
@bjmccotter7192: I did a regrouping of your page here: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2142863361/Karen+regrouping+Copy+of+VAFSC+Needed+Components+Web+Components. 

This puts the information into a table format, which I think will make it easier to see what we don't have tickets for right now and also resolve a couple of potential duplicate tickets we have right now.

**Comment by taylorkaren** [comment]
Discussed with BJ and Micah on 3/29, the https://vfs.atlassian.net/wiki/spaces/FLT/pages/2142863361/Karen+regrouping+Copy+of+VAFSC+Needed+Components+Web+Components page was updated to use for tracking work on web components in Q2.
