### ISSUE TITLE
Review Page Design Candidate Prototype and Specification

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#172]
## Context
Based on the Review Page Research Round 2 Sessions and Findings (Ticket #337), and Q2 Working Demo feedback, develop a proposed prototype and spec for the **Edit by Section** Review Page pattern (and anything else in the form structure that would tie in to the Review Page changes) to be built out in a later phase.

This is the “real thing”, post Review Page research sessions with Veterans in early Q3, and needs to account for the "simple (SSN)," not so simple (previous name)," and "complex (plot or interment allowance)" data editing scenarios.

## Task Description
- Start with mobile, then do desktop.
- Complete work before 8/26 (Kristen is on vacation 8/29 - 9/2).
- Use the Review Page Research Round 2 prototype UXPin files as the basis for this work; make a copy of these files as the starting point:
    - [Mobile](https://preview.uxpin.com/3f788e8c6673bebc0365fd5d08a28347037aa809#/pages/150422609/simulate/no-panels?mode=if)
    - [Desktop](https://preview.uxpin.com/97fe1afd9dd5b538d36e48187b4a24133e2a6bed#/pages/150370509/simulate/no-panels?mode=if)
- Resolve known issues with the prototype UXPin files
    - We have one replicable issue and several non-replicable issues
    - Don't go down a rabbit hole on these.
    - Check in during the 8/16 standup call to confirm we are on track.
- Add form pages that are missing - all form pages are included in the Q2 Working Demo UXPin files:
    - [Mobile](https://preview.uxpin.com/62a23fc3df98ec0e6916257a256070f85961318a#/pages/150522619/simulate/sitemap)
    - [Desktop](https://preview.uxpin.com/5b0d283a5e66f0f1aea71cf18f2e50e6e142f362#/pages//simulate/sitemap)
- All form pages can also be referenced in:
    - [Screen shots from the live app as of June, 2020](https://docs.google.com/document/d/1WKh1lLlaDRQ60jcIqg3yxDfYtodU1TbKoTpK1aHg1A0/edit#heading=h.1ucnchiogdno)
    - [Link to the Burial Benefits Form on va.gov](https://www.va.gov/burials-and-memorials/application/530/introduction) - we are following the unauthenticated (Start your application without signing in) path.

## Updates to include
- Team agreement on update message functionality: The update message remains on the Review Page until an action is taken; e.g., selecting an Edit link or submitting the application.
- Change the current Save and Continue title case button label to Save and continue (sentence case). 
- Anchor links on the review page should go to the appropriate section below; we didn't enable these for the research sessions, but should now because that is the intended functionality.
- Nice to have: "Blue box" messages (e.g., Your "x" has been updated text on the Review Page): Match to the styling used for [Background alert](https://design.va.gov/storybook/?path=/docs/components-va-alert--background-only) or [Background alert with icon](https://design.va.gov/storybook/?path=/docs/components-va-alert--background-only-with-icon), as applicable.

## References
- [Research Round 2 prototype page flow](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1655231826690/a747d2cd69bc3f53d4fde274e26c371a2dbfeb9d?sender=u7b7ab34685f00706a24a6128)

## Acceptance Criteria
- [x] We have a [UXPin mobile prototype]((https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745587?mode=cvhd)) of all Burial Form pages that reflect the new data editing pattern for simple, not so simple, and complex editing scenarios (link to the prototype when available).
- [x] We have a [UXPin desktop prototype]((https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/152785234?mode=cvhd)) of all Burial Form pages that reflect the new data editing pattern for simple, not so simple, and complex editing scenarios (link to the prototype when available).
- [x] We have a written summary of the core functionality of the Design Candidate on the [Phase Five section on the Model Form Design Mockups and Prototypes for Q2 working demo Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2160099329/Model+Form+Design+Mockup+for+Q2+working+demo#Phase-Five).
- [x] Add links to the UXPin files on the relevant transition pages in Confluence (Karen - Transition Plan and VAFSC Work Stream pages)
- [x] Add link(s) to the Confluence page information on the relevant transition pages in Confluence (Karen - Transition Plan and VAFSC Work Stream pages)

**Comment by taylorkaren** [comment]
Hey @kristen101606 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by kristen101606** [comment]
The prototypes are ready for review. The links are included in https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/583 and also listed here for convenience: 
- **Mobile:** https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745587?mode=cvhd
- **Desktop:** https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/152785234?mode=cvhd

**Comment by taylorkaren** [comment]
Re-opening this ticket because two items on the Acceptance Criteria list have not been addressed:
We have a written summary of the core functionality of the Design Candidate in Confluence (this can be in the [Phase Five section on the Model Form Design Mockups and Prototypes for Q2 working demo Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2160099329/Model+Form+Design+Mockup+for+Q2+working+demo#Phase-Five) or on a separate Confluence page that is linked from the [Phase Five section on the Model Form Design Mockups and Prototypes for Q2 working demo Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2160099329/Model+Form+Design+Mockup+for+Q2+working+demo#Phase-Five).
- [ ] Update info in the [Phase Five section on the Model Form Design Mockups and Prototypes for Q2 working demo Confluence page]
