### ISSUE TITLE
[JSON Schema Support] Pass schema properties in as initialValue

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#173]
## Description
A fundamental part of how forms work on VA.gov is the use of jsonschema. Serving as a sort of contract between what the frontend sends and what the backend receives, jsonschemas help define what payload properties are: string, boolean, number, etc. 

A core piece of Formik is supplying `initialValues` to use within a form, mapping DOM elements to form values for use with Formik's render methods. 

VA Forms System Core needs to support the continued use of jsonschema. This will be achieved by consuming a given schema, extracting its properties, and passing those into Formik as one object of initial values.

## Considerations
- May not need a helper function to pass properties in. Could potentially just use something like `schema.properties`
- `FormRouter` accepts a `formData` prop which is ultimately used for initial values. It may be good to rename this so it's purpose is clearer. 

## Tasks
- [ ] Create a way to pass `schema.properties` into Formik as initial values 
- [ ] Copy the burials dist json-schema into VAFSC 
- [ ] Write tests that ensure form is rendering with expected field values
- [ ] Add any documentation, JSDoc is fine for now, around any gotchas discovered around passing in schema properties as initial values

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main

**Comment by micahchiang** [comment]
Updated this ticket to only be responsible for consuming schema properties, and created #312 to handle transformForSubmit functionality.

**Comment by micahchiang** [comment]
staging.va.gov/burials-and-memorials/application/530

**Comment by nickjg231** [comment]
PR here: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/334
