### ISSUE TITLE
(For release package 1.0.0) Semantic Versioning and Automatic NPM Publishing

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/va-forms-system-core#184]
## Description 
We need to set up semantic versioning in the va-forms-system-core repository to align the Github Releases with the NPM publish version. This will allow us to have automated publishing when a changed gets merged into the master/main branch.

## Considerations
- VA VSP Github Token 
- VA VSP NPM Token
- https://vfs.atlassian.net/wiki/spaces/FLT/pages/1992163490/New+Forms+Library+fka+Formulate+Semantic-Release+Idea

## Tasks
- Add semantic versioning to project
- Get access to tokens
- Alter NPM publish github action

## Acceptance Criteria
- [ ] Semantic versioning has been added to project
- [ ] NPM package version gets upgraded with every merge to master
- [ ] FLT members have reviewed and provided feedback:
    - [ ] BJ
    - [ ] Harshil
    - [ ] Karen
    - [ ] Lauren
    - [ ] Micah
    - [ ] Nick
    - [ ] Susanna

**Comment by taylorkaren** [comment]
This ticket is superseded by ticket #432.
