### ISSUE TITLE
(Comms at the end of the 3/31 sprint) Forms Library Support: Craft Support Policy and Communication Strategy

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#187]
## Task Description
Craft a clear policy and communication strategy regarding the Forms Library Team support of the current Forms Library to be sent out to application teams.

## Considerations
- Our intentions: active development on the current Forms Library will end. Unless there are production breaking bugs uncovered, active feature iteration is ending.
- Support requests that are around "how to do a thing in the Forms Library" will be time boxed to roughly 30 minutes. 
 - App teams should have clear expectations set for them that the current Forms Library is officially in maintenance mode. Teams are still welcome to use it to achieve roadmap OKRs, but again, feature requests will not be worked on.
- See the [VFS Platform Support Process page](https://vfs.atlassian.net/wiki/spaces/AP/pages/2026864690/VFS+Platform+Support+Process?atlOrigin=eyJpIjoiNjQ0YWVlYTRlMjZkNDg0ODhhZmNjN2E1NTE2MTQ1ZWYiLCJwIjoiYyJ9) for additional guidance to consider including in the communication.
- Platform support is working on providing guidance that tells VFS engineers which types of questions should be directed to which team: https://dsva.slack.com/archives/CJRQ85PQB/p1648153187796389.

==================================================================
**WHAT LEVEL OF SUPPORT DO WE PROVIDE FOR CUSTOM COMPONENT WORK ([Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1649080851567139))?**

## Acceptance Criteria
- [x] A Forms Library Support policy is defined on a page on the FLT Confluence site (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2129920044/Forms+Library+Support). We may want to think about establishing Support as a top level page, with this policy being some of the content on that top level page.
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] The Forms Library Support policy has been communicated to application teams via the following methods:
    - [x] Announcement in the DS VA #vfs-platform-support, #vfs-all-teams, #vsp-design-system, #vfs-front-end, #vfs-designers, #pst-forms-library, and #vfs-engineers Slack channels.
    - [x] Announcement in the Team of Teams call. (4/12/22)
- [x] Coordinate with the Design System Team to update the support page(s) in their Confluence space to reflect the change in who is doing Forms Library support and link to the relevant page(s) in the Forms Library Team Confluence site.

**Comment by micahchiang** [comment]
https://vfs.atlassian.net/wiki/spaces/FLT/pages/2129920044/Forms+Library+Support

**Comment by bjmccotter7192** [comment]
Seems like a good plan to me @micahchiang

**Comment by taylorkaren** [comment]
4/12 standup: Micah will coordinate with Katy on the DST Confluence page updates and send messages to the Slack channels tomorrow (4/13).
