### ISSUE TITLE
(Materials from Katy?) Forms Library Support: Define Rotation Support Approach and Schedule

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#188]
## Task Description
- Define Forms Library support commitment by the Forms Library Team. We can look at this page in the Design System Team Confluence space as a model: https://vfs.atlassian.net/wiki/spaces/DST/pages/1974337674/Design+System+Team+support+rotation 
    - Should include guidance on how to time box issues, where to send people for documentation, etc.
    - Reference the https://depo-platform-documentation.scrollhelp.site/support/Support-overview.604012552.html page
- Define the length of our support rotations and set up a schedule for who is on support when. We can look at this page in the Design System Confluence space as a model: https://vfs.atlassian.net/wiki/spaces/DST/pages/2027946432/2022+Support+Rotation+Schedule.
    - Let the Design System Team know who the point person will be during the ridealong sprint starting on 3/31.

## Considerations
 - Distinguish FLT support for Forms Library from DST support for Design System. Expect that we will need to hand tickets back and forth when they first come in to the wrong team.
- Plan is for the Forms Library Team to “ridealong” on Forms Library support tickets during the sprint that starts on 3/31, and take over all Forms Library support tickets during the next sprint, starting on 4/14.
- Katy will send over support rotation info so the Forms Library Team can set up a similar approach.

## Acceptance Criteria
- [x] Forms Library support commitment by the Forms Library Team is documented on a Confluence page in the Forms Library Support section (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2129920044/Forms+Library+Support) of the FLT space. 
- [x] Forms Library support rotation is documented on a Confluence page in the Forms Library Support section (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2129920044/Forms+Library+Support) of the FLT space. 
- [x] When these docs are done, let the Design System Team know where they are and who will be the "ridealong" FLT support engineer during the sprint that begins on 3/31.

**Comment by micahchiang** [comment]
FLT support policy - https://vfs.atlassian.net/wiki/spaces/FLT/pages/2129920044/Forms+Library+Support.

@bjmccotter7192 and @sdk-irl to ride-along with the DST.
