### ISSUE TITLE
POC walkthrough

### ISSUE THREAD

**Issue by biannuz** [department-of-veterans-affairs/va-forms-system-core#191]
## Task List
- [x] Walkthrough meeting with Matt on 3/23 to review the screenshots on the [Endgame Scenario: Greenfield page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2079555975/Endgame+Scenario+Greenfield) and the [presentation slide deck](https://docs.google.com/presentation/d/12bB90enebne1Q7Iymj4mEkeiUXf9wqoAgBuAvsdj4B0/edit#slide=id.g892adcb623_0_141), and talk about how we want to present this information in the Design + Content + Research Sync meeting on Monday, 3/28 @ 1pm.
- [x] Use notes from the 3/28 meeting to write up a [Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2139979788/Meeting+Notes+Form+Builder+Proof+of+Concept+Presentation+to+the+VA.gov+Platform+and+Apps+Weekly+Design+Content+Research+Sync) about what we learned from presenting this hypothetical future state drag/drop form builder to this audience.
- [x] Include the [PDF version of the slides](https://app.zenhub.com/files/375815514/b9291706-b0c4-4dd1-882f-f92861163d21/download) and a link to the [presentation slide deck](https://docs.google.com/presentation/d/12bB90enebne1Q7Iymj4mEkeiUXf9wqoAgBuAvsdj4B0/edit#slide=id.g892adcb623_0_141) on the Confluence page.

## Notes
- Be prepared for detailed questions about what this app would do. Answer: At the moment, it does nothing, because it is just a proof of concept. But...hearing those questions would give us some good ideas about what it maybe should do, so make sure we call out good suggestions in the Confluence writeup.
