### ISSUE TITLE
Analysis: Investigate options to provide some sort of playground or more documented examples of how to build forms using the VAFSC

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#202]
## Task Description
Investigate options to provide some sort of playground or more documented examples of how to build forms using the VAFSC and document findings on a Confluence page.

## Considerations
- This would be part of the documentation for the new VA Forms System Core.
- Starter list of approaches to investigate **_(add more as we think of them)_**:
    - JSFiddle? (https://jsfiddle.net/)
    - Drag and drop components in the browser?
    - Get a test app stood up?

## Acceptance Criteria
- [x] Approaches listed in the Considerations section have been investigated and summarized on a Confluence page in the [Product Docs section of the FLT Confluence space](https://vfs.atlassian.net/wiki/spaces/FLT/pages/1992163480/Product+Docs) that:
    - [x] Describes each approach
    - [x] Outlines what steps would need to be taken to set up each approach, with a rough LOE
    - [x] Defines the pros and cons of each approach
- [x] The page has been reviewed by FLT members ([Link to staging draft](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2289106971/Playground+Environment+Documentation+Investigation)):
    - [x] Anish
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
- [x] FLT member feedback has been addressed.

**Comment by obliviga** [comment]
LGTM, great work on this @nickjg231 !

**Comment by bjmccotter7192** [comment]
well done document @nickjg231 !

**Comment by micahchiang** [comment]
great work @nickjg231
