### ISSUE TITLE
Check Box Group

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#203]
## Description
Should have the same look as already established on [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-checkbox-group--default). Work is to wrap the radio group in the Formik wrapper, not change anything with the look and feel.

<details><summary>Checkbox Group UI</summary>

![Screen Shot 2022-03-25 at 12.04.38 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/dafeedd3-dac8-4d9f-8dd4-abe9defb2836)
![Screen Shot 2022-03-25 at 12.04.49 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/74b612d9-355b-4beb-91d9-a20997d6cb30)
</details>

## Considerations
- Learning for the Array Field object that will be done at a later time.
- DST will be updating the `va-checkbox-group` component to use native HTML events within the next two sprints
- The `va-checkbox-group` can take as many `va-checkbox` components as needed
- Should validate at least one item is selected
- [va-forms-system-core CheckboxField](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/5aad5bf6ecd1db653fae60f9c3b337d7258da892/src/form-builder/CheckboxField.tsx#L2)
- [va-forms-system-core CheckboxField unit tests](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/b95fb7fb5b792a57fc52075a9ab3230e8b6282d5/test/form-builder/CheckboxField.test.tsx#L2)
- The `CheckboxGroupField` needs to be able to take something like an array of options and return a list of checkboxes, something like:
```
// pseudocode
const CheckboxFieldGroup = (props: CheckboxGroupProps): JSX.Element => {
  return (
    <VaCheckboxGroup>
      {
        props.options.map(option => (<CheckboxField {...option.props}>option</CheckboxField>))
      }
    </VaCheckboxGroup>
  )
}
```

## Tasks
- [ ] Write a `CheckboxGroupField` that accepts any number of checkboxes, and validates at least one is selected
- [ ] Write unit tests for the `CheckboxGroupField`
- [ ] Include code block declarations for automatic documentation generation
- [ ] Add learning for the Array Field object that comes out of work on this ticket to the Placeholder Array Field ticket (#238).

## Acceptance Criteria
- [ ] above tasks have been completed
- [ ] PR has been merged into va-forms-system-core

**Comment by taylorkaren** [comment]
PR for this ticket: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/245.
Note that we need to update the version of the component library in our package.json file as part of this PR.
