### ISSUE TITLE
Field: Telephone

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/va-forms-system-core#210]
## Description
This is going to be the new Telephone similar to the current Telephone in forms-library.

### UI
![Screen Shot 2022-03-29 at 10.14.01 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/9c623709-2a2c-40dd-a560-09c6270443d0)
![Screen Shot 2022-03-29 at 10.14.11 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/ed4418d1-d3ce-4e55-ab25-ace2940ab6a5)

## Considerations
- Use the web components to create a custom Telephone field that will have built in validation.
- [design.va.gov guidance](https://design.va.gov/patterns/form-patterns#phone-numbers) on phone numbers
- [Current phone validator](https://github.com/department-of-veterans-affairs/vets-website/blob/023e288d7f88da52a285983aff5d94880dc3c169/src/platform/forms/validations.js#L182)
- Validation messages:
  - `required`: Please enter a phone number
  - `pattern`: Please enter a 10-digit phone number (with or without dashes)
- [va-forms-system-core validations file](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/5aad5bf6ecd1db653fae60f9c3b337d7258da892/src/utils/validation.ts#L1) is where a validator should be included
- The above validation messages should be included in the [va-forms-system-core messages file](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/5aad5bf6ecd1db653fae60f9c3b337d7258da892/src/messages/en.ts#L3)

## Tasks
- [x] Write a `Telephone` similar to the current Telephone in forms-library.
- [x] Write unit tests for the `Telephone`
- [ ] Include code block declarations for automatic documentation generation

## Acceptance Criteria
- [ ] above tasks have been complete
- [ ] PR has been merged into va-forms-system-core
