### ISSUE TITLE
Field: SSN

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/va-forms-system-core#212]
## Description
As a user, I want to enter my SSN with or without dashes, and I want the numbers to be masked so I know it's protected from others looking at it. 

<details><summary>SSN UI taken from 28-8832 form</summary>

![Screen Shot 2022-03-29 at 9.41.36 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/30195bcb-4dde-4929-abe0-059645438d2d)
![Screen Shot 2022-03-29 at 9.42.35 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/d67986a5-66ff-4fa6-abdf-7931d16181a0)
![Screen Shot 2022-03-29 at 9.46.14 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/0415b35e-05b1-4198-a541-d897b62f4e6a)
![Screen Shot 2022-03-29 at 9.42.23 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/25a88451-d809-47e0-a2f4-7fe9b6d9b1ae)
![Screen Shot 2022-03-29 at 9.42.08 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/acb76c21-68a7-4c7e-b377-cab1af129961)
![Screen Shot 2022-03-29 at 9.41.50 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/74f96d92-c863-4b21-b3a4-00d2fab847b4)
</details>

## Considerations
- Use the web components to create a custom ssn field that will have built in validation.
- [design.va.gov](https://design.va.gov/patterns/form-patterns#important-numbers-social-security-number--va-file-number) guidance for social security number form field.
- Input should support SSN's entered with and without dashes. 
- Entire number except the last 4 numbers should be obscured, see attached UI. This happens during `onBlur` or after focus changes.
- Validation messages:
  - `required`: Please enter a Social Security number.
  - `pattern`: Please enter a 9 digit Social Security number (dashes allowed).
- [Current function used to mask SSNs](https://github.com/department-of-veterans-affairs/vets-website/blob/757fb3528ae34570cf9f7c712ff4e24ce7ad662b/src/platform/forms-system/src/js/widgets/SSNWidget.jsx#L9)
- [Current SSN validator](https://github.com/department-of-veterans-affairs/vets-website/blob/f4b25cbd64eae96dc2e25884903723ca80485dca/src/platform/forms-system/src/js/utilities/validations/index.js#L13)
- We may be able to just copy the current SSN validator into the va-forms-system-core [validations file](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/5aad5bf6ecd1db653fae60f9c3b337d7258da892/src/utils/validation.ts#L1)
- Field validation messages should be store in the [validation messages file](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/5aad5bf6ecd1db653fae60f9c3b337d7258da892/src/messages/en.ts#L3)

## Tasks
- [ ] Write a `SSNField` that has validation around ssn type inputs
- [ ] Write unit tests for the `SSNField`
- [ ] Include code block declarations for automatic documentation generation

## Acceptance Criteria
- [ ] above tasks have been complete
- [ ] PR has been merged into va-forms-system-core

**Comment by nickjg231** [comment]
PR/branch open here:
https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/281

Things to do still:
- Finish validation (I added the `isValidSSN` function but haven't made it work yet. It may need some changes).
- Write test cases
- Remove eslint suppression statements in `SSNField.tsx`'s onblur function
- Update documentation/comments if necessary
