### ISSUE TITLE
Field: Email

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/va-forms-system-core#213]
## Description
This is going to be the new EmailField similar to the existing `Email` field in RJSF.
<details><summary>Email UI taken from 28-8832 Form</summary>

![Screen Shot 2022-03-29 at 9.28.29 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/7af6fffe-81f7-4635-8e5b-c9820dc8333f)
![Screen Shot 2022-03-29 at 9.30.47 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/00dbb799-8eca-4d20-90f3-1f79f8ce1a48)
![Screen Shot 2022-03-29 at 9.31.36 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/d4aa20c0-02b8-42a1-98e3-7a06c7023860)
![Screen Shot 2022-03-29 at 9.32.43 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/33b09ff5-2c50-478c-a5ba-5815a90f5455)
</details>

## Considerations
- Use the web components to create a custom email field that will have built in validation.
- [Current validation used for emails](https://github.com/department-of-veterans-affairs/component-library/blob/15d606e04ea012c1fb8242bd390103a67010b0e6/packages/react-components/src/helpers/validations.js#L306-L312)
- va-forms-system-core already has a [validations file](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/5aad5bf6ecd1db653fae60f9c3b337d7258da892/src/utils/validation.ts#L1). We may want to consider adding a `validateEmail` function in here to keep all validator in one place.
- va-forms-system-core already has a [messages object](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/5aad5bf6ecd1db653fae60f9c3b337d7258da892/src/messages/en.ts#L3) that internal validations pull their error messages from. We may want to consider adding an error message for email pattern here. 
- [design.va.gov/patterns/messaging-directory](https://design.va.gov/patterns/messaging-dictionary) dictates the error message for an invalid email address should be "Please enter a valid email address"
- It's common on digital VA forms to ask users to confirm their email address by re-entering it on a second field. We may want to provide an internal way of validating that an email field and a `confirmEmail` field hold the same value. 

## Tasks
- [x] Write an `EmailField` that has validation around email type inputs
- [x] Write unit tests for the `EmailField`
- [x] Include code block declarations for automatic documentation generation

## Acceptance Criteria
- [ ] above tasks have been complete
- [ ] PR has been merged into va-forms-system-core

**Comment by nickjg231** [comment]
PR open here:
https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/265
