### ISSUE TITLE
Field: Address

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/va-forms-system-core#216]
## Description
This is going to be the new AddressField similar to the existing `Address` field in RJSF. Addresses on VA.gov need to handle the following scenarios:
### Standard USA address
<details><summary>UI</summary>

![Screen Shot 2022-03-28 at 3.46.11 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/e3f52209-0f31-4ffb-893a-42939656447a)
</details>

- Street 1 required
- City required
- State Required, this dropdown needs to include all states, DC, *and* US territories. 
- Postal code (zip) required

### United States military base outside of the United States
<details><summary>UI</summary>

![Screen Shot 2022-03-28 at 4.02.28 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/69ac2e68-52af-4d73-85f4-566c6e552bec)
</details>

- Street 1 required
- Instead of a City field, a select tag with:
  - required
  - Label: APO/FPO/DPO
  - Option tags with [these values](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/f12ddceab9bdde983dd33b1ab13a31313aec6d65/src/common/address.js#L258)
- State, required, with [these options](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/f12ddceab9bdde983dd33b1ab13a31313aec6d65/src/common/address.js#L252-L256)

### Non United States address
<details><summary>UI</summary>

![Screen Shot 2022-03-28 at 4.11.32 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/98fc3b0e-14c6-417e-8613-3754168380ef)
</details>

- Street 1 requried
- City required
- Postal code required

## Considerations
- Use the web components to create a custom address field that will have built in validation.
- [All address data](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/f12ddceab9bdde983dd33b1ab13a31313aec6d65/src/common/address.js#L370) related to countries, territories, states, provinces, branches of military.

## Tasks
- [ ] Write an `AddressField` that has validation around address type inputs
- [ ] Write unit tests for the `AddressField`
- [ ] Include code block declarations for automatic documentation generation

## Acceptance Criteria
- [ ] above tasks have been complete
- [ ] PR has been merged into va-forms-system-core
