### ISSUE TITLE
Field: Date

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#220]
## Description
Dates are an integral part of filling out forms on VA.gov. The DST has recently completed the [va-date component](https://design.va.gov/storybook/?path=/docs/components-va-date--default) so we need to create the corresponding form component.

## Considerations
- New web component info: https://design.va.gov/storybook/?path=/docs/components-va-date--default.
- [Migration guide for simpledate to va-date](https://vfs.atlassian.net/wiki/spaces/DST/pages/2127527996/Manual+Component+Migration+Guide#Date-or-SimpleDate-to-va-date%3A). Unsure if this will be needed
- va-date will need to be wrapped in Formik similar to all of our other form fields
- Date field should have a dynamic label. Something like `props.label` that gets passed into the label prop directly on the web component
- Date component should be able to handle common validity cases including but not limited to:
  - Date of death cannot be before date of birth
  - Date of marriage cannot be before date of birth
  - Service start date cannot be after service end date
  - Service end date cannot be before service start date

<details><summary>Example UI</summary>

![Screen Shot 2022-05-09 at 10.27.38 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/ca1f1ac0-7a41-408b-a2f0-b0d278433fa2)
</details>

## Tasks
- [ ] Import and use va-date to build the new VAFSC date component
- [ ] Write unit tests to handle validation cases

## Acceptance Criteria 
- [ ] Tasks have been completed
- [ ] PR has been merged

**Comment by taylorkaren** [comment]
From the 4/29/22 DST sync call: DST had the staging review for the updated Date web component this week. Finishing up some accessibility fixes, should be ready next week (week of 5/2),
