### ISSUE TITLE
Working Demo Review Page Mockup

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#227]
## Task Description
-  **Create a copy** of the [UXPin file used for Review Page Veteran user testing in May, 2022](https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/149929272/simulate/sitemap?mode=i) to use as the starting point for this work. - DONE
- Keep all of the form pages, remove the review pages that are not [Design #3] - DONE (https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/150052471/simulate/sitemap?mode=i).
- Include desktop and mobile screen mockups for all pages. -DONE
---------------------------------------------------
- Per discussion with Matt in the 5/20/22 PO sync call, use [Design #3](https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/150052471/simulate/sitemap?mode=i) for the Review Page layout and design.
    - Use Edit as the link text in each section, as shown in the design. - DONE
    - Selecting Edit takes you back to the appropriate form page. - DONE
    - All fields on the form page that you go to from the Edit link on the Review Page can be edited. - DONE
    - There is some means to navigate back to the review page after making a change on the form page.
        - For the working demo, assume no impact on form logic as a result of the update, we will not design for that path at this time. - DONE
---------------------------------------------------
- The Review Page as shown in the current [Design #3](https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/150052471/simulate/sitemap?mode=i) needs to be updated to include the correct information in the following sections, so that the review page includes the same information as the corresponding form page:
    - Deceased Veteran information: Add Place of birth, Date of death, Date of burial, Where did the Veteran's death occur - OK. Place of birth not included, but it is an optional field on the form and our rules for displaying optional info on the review page is that it only appears when information has been entered.
    - Military History: Should only be information that can be entered in the fields on these form pages (there is a lot of other information in this section right now that is not entered on this form): https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/149929280/simulate/sitemap?mode=i and https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/149929279/simulate/sitemap?mode=i - **_SERVICE HISTORY TO BE ADDED_**
    - Benefits Selection: This section needs to be added. Should only be information that can be entered in the fields on these form pages: https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/149929278/simulate/sitemap?mode=i, https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/149929277/simulate/sitemap?mode=i, and https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/149929276/simulate/sitemap?mode=i - DONE
    - Additional information: This section needs to be added. Should only be information that can be entered in the fields on this form page: https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/149929275/simulate/sitemap?mode=i. - DONE
- **_NEED TO REMOVE THE DOCUMENT UPLOAD SECTION FROM THE MOBILE AND DESKTOP VERSIONS_**

## Considerations
- This mockup will reflect where we **think** we may be heading for a pattern update. It is not definitive, as timing dictates that we make a best guess on this after having done only an initial research effort.
- We are not building any significant functionality at this time that goes beyond the review page itself other than coding an edit link to go back to a form page and then return to the Review page.
- The primary intent is for the working demo page to be a visual mockup in code so that we can present it at the end of a form entry flow.
- Building this in code will provide the ability to do accessibility checks on the code side.

## Acceptance Criteria
- [x] We have a UXPin [desktop](https://preview.uxpin.com/5b0d283a5e66f0f1aea71cf18f2e50e6e142f362#/pages/150714467/simulate/sitemap) and [mobile](https://preview.uxpin.com/62a23fc3df98ec0e6916257a256070f85961318a#/pages/150534574/simulate/sitemap) mockup of all Burial Form pages, including the [Design #3](https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/150052471/simulate/sitemap?mode=i) version of the Review Page, that we will build in the working demo version of the first iteration of the VA Forms System Core that matches the Task Description above.
- [x] Update info in the [Phase Three section on the Model Form Design Mockup for Q2 working demo Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2160099329/Model+Form+Design+Mockup+for+Q2+working+demo#Phase-Three).
- [x] Add a link to the desktop working prototype to the [Working Demo Product Summary page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2208432137/VA+Forms+System+Core+Q2+2022+Working+Demo+Product+Summary)

**Comment by taylorkaren** [comment]
Created https://vfs.atlassian.net/wiki/spaces/FLT/pages/2160099329/Form+Design+Mockup+for+Q2+working+demo to capture details about this work.

**Comment by taylorkaren** [comment]
Moved to Blocked status - we are working on the Review Page Research Round 2 prototypes before coming back to the cleanup items on this ticket.

**Comment by taylorkaren** [comment]
@KavithaKrishnan: These are the final cleanup tasks to be done on the Q2 Working Demo mockups:
- [ ] [Desktop Review Page](https://preview.uxpin.com/62a23fc3df98ec0e6916257a256070f85961318a#/pages/150534778/simulate/sitemap): Add a Military History section between the Deceased Veteran Information and Burial Information sections. You can copy and paste the Military History section information from this page: https://preview.uxpin.com/97fe1afd9dd5b538d36e48187b4a24133e2a6bed#/pages/150528890/simulate/sitemap.
- [ ] [Desktop Review Page](https://preview.uxpin.com/62a23fc3df98ec0e6916257a256070f85961318a#/pages/150534778/simulate/sitemap): Remove the Document Upload section.
- [ ] [Mobile Review Page](https://preview.uxpin.com/62a23fc3df98ec0e6916257a256070f85961318a#/pages/150534574/simulate/sitemap): Add a Military History section between the Deceased Veteran Information and Burial Information sections. You can copy and paste the Military History section information from this page: https://preview.uxpin.com/3f788e8c6673bebc0365fd5d08a28347037aa809#/pages/150422644/simulate/sitemap.
- [ ] [Mobile Review Page](https://preview.uxpin.com/62a23fc3df98ec0e6916257a256070f85961318a#/pages/150534574/simulate/sitemap): Remove the Document Upload section.
