### ISSUE TITLE
Review Page Research Plan + UXPin Prototypes

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#229]
## Task Description
- Create a plan for Review Page research with Veterans. 
- Matt will create some Review Page pattern variations (these will be in the https://www.sketch.com/s/09640425-48be-4019-8277-8a924eff1df7/p/E495CB14-1751-48E0-8DF9-20D17C87B37A/canvas Sketch file) for inclusion in the research plan documentation.

## Considerations
Lauryl can provide orientation and training for doing research with Veterans. Please reach out to her for this information and take it into consideration when developing the research plan.

## Acceptance Criteria
- [x] A Review Page research plan is detailed on a page in [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/pst-forms-library/research/review-page/research-plan.md).
    - [x] The research plan follows standard VA guidelines for doing research with Veterans.
    - [x] The research plan includes links to the UXPin Prototypes that will be used for testing with Veterans.
- [x] A conversation guide for the research sessions is detailed on a page in [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/pst-forms-library/research/review-page/conversation_guide.md).
- [x] A Confluence page is included in the [Research section of the FLT Confluence space](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2149548058/Research) that provides a summary of the research to be done and links to the relevant documents in GitHub. (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2179399822/Review+Page+Research)

**Comment by taylorkaren** [comment]
Review comments, 5/2/22:
**Conversation Guide** (https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/teams/vsp/teams/pst-forms-library/research/review-page/conversation_guide.md)
	•	Need to add a link to the Mural Board for notes
	•	“Participant will fill out 3 pages in this form” - but we have more than 3 pages in the UXPin prototype. Please trim down the number of pages in the UXPin prototype.

**Research Plan** (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/pst-forms-library/research/review-page/research-plan.md)
	•	Still viable to do a pilot session tomorrow?

Per the ticket acceptance criteria, a Confluence page needs to be included in the Research section of the FLT Confluence space that provides a summary of the research to be done and links to the relevant documents in GitHub.
