### ISSUE TITLE
[Q2 Demo Prep] Build Review Page

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#231]
## Task Description
- Build the Q2 Working Demo Review page, following the mockups developed on ticket #227:
    - [Mobile](https://preview.uxpin.com/62a23fc3df98ec0e6916257a256070f85961318a#/pages/150534574/simulate/sitemap)
    - [Desktop](https://preview.uxpin.com/5b0d283a5e66f0f1aea71cf18f2e50e6e142f362#/pages/150714467/simulate/sitemap)
- Per discussion with Matt in the 5/20/22 PO sync call, for the Q2 working demo we will design and build as follows: 
    - Use [Design #3](https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/150052471/simulate/sitemap?mode=i) for the Review Page layout and design.
    - Use Edit as the link text in each section, as shown in the design (note that enabling editing capability will be handled on ticket #342)
- Required fields always appear on the review page - label and value
- Optional fields appear on the review page only when data has been entered for the field - label and value
- Conditional fields appear on the review page only when data has been entered for the field - label and value
-  Include a Skip option to go directly to the Submit button?
- When you go back to a page in the form, the Back to Review page button MUST work. Back and Next nav buttons are nice to have for the working demo.

## Considerations
- This mockup will reflect where we **think** we may be heading for a pattern update. It is not definitive, as timing dictates that we make a best guess on this after having done only an initial research effort.
- Think of this page as mostly being a visual mockup in code.
- We should be able to do some basic accessibility checks on the code side to confirm correct implementation of things like labels on all buttons, links and headers for screen reader accessibility.
- Ensure meaningful error feedback is provided.

## Acceptance Criteria
- [ ] Tasks complete
- [ ] PR has been merged into main
- [ ] When a user completes the form pages included in the Q2 Working Demo (as listed on ticket #259), a review page that matches the provided mockup is presented.
- [ ] Check off the checkbox on #259 to mark page as complete
