### ISSUE TITLE
Create How-To Document Code in VAFSC 

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/va-forms-system-core#234]
## Description
Create a Markdown file inside of the VAFSC Automated Docs site ( https://department-of-veterans-affairs.github.io/va-forms-system-core) that explains how to add documentation to your code. 

## Considerations
Review the following information about API Extractor:
- [API Extractor](https://api-extractor.com/)
- [Sample API Extractor Project](https://api-extractor.com/pages/overview/demo_project/)
- Commit hook that complains if you don't include a jsdoc comment around any new functionality.

## Tasks

- [ ] Create How-to-document-code here: https://department-of-veterans-affairs.github.io/va-forms-system-core/how-to-guides/

## Acceptance Criteria

- [ ] Should be able to properly document a newly created component/field/definition/type and have it show up in the documentation website
- [x] Draft PR has been reviewed by FLT members:
    - [x] Anish
    - [x] BJ
    - [x] Harshil
    - [x] Lauren 
    - [x] Micah
    - [x] Nick
- [x] All feedback has been addressed.
- [ ] Draft PR --> "real PR"
- [ ] "Real" PR has been merged.

**Comment by taylorkaren** [comment]
Micah sent link to engineers for their review.

**Comment by bjmccotter7192** [comment]
Looks good so far just left one comment about live examples.

**Comment by obliviga** [comment]
LGTM, I agree with @bjmccotter7192's feedback.

**Comment by taylorkaren** [comment]
Re-opened because the PR is still in draft and has not been merged.
