### ISSUE TITLE
forms.va.gov domain for VAFSC documentation?

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#244]
## Description
Currently FLT has some automation setup around code documentation that gets generated on build and deployed to this website: [VAFSC - Code Docs](https://department-of-veterans-affairs.github.io/va-forms-system-core/) 

The initial ask for this ticket was to figure out where we need/want to move this site, in response to reducing the amount of documentation sprawl (Confluence, Github, Github Pages, design.va.gov). 

After some discussion with members of the Design System Team, and FLT members we have decided it will be best to figure out a way to add our documentation to the design.va.gov, by either a sub path `ex. design.va.gov/forms` and possibly a navigation button. This will help tie the Design System and the Forms Library Team docs together.

## Useful Links
- [FLT - Confluence Documentation Domain Change](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2163376393/Code+Documentation+Domain)
- [Current Design System Team Documentation Repo](https://github.com/department-of-veterans-affairs/vets-design-system-documentation)
- [Current FLT Code Documentation](https://department-of-veterans-affairs.github.io/va-forms-system-core/)
- [API-Extractor](https://api-extractor.com/)
- [TypeDoc](https://typedoc.org/)
- [Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1650468264731399)

## Considerations
- API-Extractor may or may not be the best tool (need to get markdown files generated with all the required front matter)
- VAFSC is using Jekyll as well to generate the website, BUT we will need to fit the model for the design system docs
- Make it easy for non-Forms Library engineers to contribute to documentation.
- Does design.va.gov/forms have to be the place for the VAFSC automated documentation? What makes sense to locate there (maybe the same type of Forms Library docs we've put up on the Platform documentation site; e.g. the How To guides)?
- Don't need this immediately, VAFSC docs are still a ways off. We are planning for the future right now.

## Acceptance Criteria
- [x] Write tickets for follow on tasks, from the 4/29/22 DST/FLT Sync Call discussion:
    - [x] Define where the curated space for the VA Forms System Core documentation should reside on design.va.gov (#277)
    - [x] Figure out how best to automate FLT documentation on the Design System Jekyll site  - set aside some time for this in an upcoming sprint to work with DST on this (#278)
        - [x] Can VAFSC produce markdown files automatically on build?
        - [x] Can markdown files be automatically deployed to the documentation repository and design.va.gov site?
        - [x] Remove/deprecate the [Current FLT Code Documentation Github Page](https://department-of-veterans-affairs.github.io/va-forms-system-core/)?
    - [x] Markdown format: This picks up what was discussed in the [Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1650468264731399): How do we get front matter into our markdown files (automated or manual process?) and are our markdown files in a format consistent with design.va.gov (if not, how do we get them into a consistent format?) (#279)

## Potential areas of exploration for the Figure out how best to automate FLT documentation on the Design System Jekyll site ticket: 
- Update API-Extractor to produce JSON manifest of all docs OR Use another tool to do similar
- Write a mapper that takes in JSON and produces markdown files 
- Create github action inside of VAFSC to move markdown files to AWS S3 bucket in the correct location (MAYBE?)
- IF we don't write an action, figure out a more streamline way to deploy documentation.

**Comment by bjmccotter7192** [comment]
Here is the write up for the research done on this ticket: 
https://vfs.atlassian.net/wiki/spaces/FLT/pages/2163376393/Code+Documentation+Domain

**Comment by taylorkaren** [comment]
I talked about this with Matt during the PO sync call this morning, and here is the summarized feedback:
Discussion:
	•	Preference is for automatically generated markdown files to be incorporated in the Design System documentation. 
	⁃	There are already two GitHub repos, Confluence, Storybook and Sketch to look at, we want to consolidate where documentation lives, not continue with many disparate locations.
	•	We could go with something like design.va.gov/forms and redirect form there to GitHub if necessary. 
	⁃	Preference is to include the help files themselves on the design.va.gov site and have them pulled in to that location. 
	⁃	DST/FLT conversation to figure this out.
	•	Also think about moving the current Forms Library documentation from the Confluence Developer Docs site to wherever the new documentation will be, once we figure that out.
