### ISSUE TITLE
Q1 metrics follow-up Part 2: April - July 2022 Stats

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#246]
## Task Description
- Compile April - July 2022 stats on Forms Library support requests logged in the #vfs-platform-support channel.
- This will give us the snapshot of metrics after the updated Forms Library documentation was available in the [VA Forms Library section of the Developer Docs Platform Website](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System-Overview.2085355587.html).

## Considerations
- Source doc is the [Platform Support Responses sheet](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=0).
- Use the [Q1 metrics page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2051538980/Q1+2022+Baseline+KRs) as guidance to derive the same stats, based on platform-support channel requests, for the mid-April to mid-July 2022 time frame so that we can see what the support requests related to Forms Library looked like during the quarter after the new docs were available.
- We will compare these metrics to the metrics for the quarter before the new documentation was available (ticket #190) to determine if the updated documentation had any impact in the number and nature of Forms Library support requests.
- **NOTE** that the Forms Library Team took over support for the Forms Library as of 4/14/22, so requests after that date will be coded with Forms Library as the Topic, rather than Design System.
- May also want to look at analytics for the new pages (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System-Overview.2085355587.html and all of its child and grandchild pages to see how much traffic they are getting).
    - [Google Analytics](https://analytics.google.com/analytics/web/#/report-home/a50123418w224573768p240292331)
    - [DOMO](https://va-gov.domo.com/page/1182586883)

## Acceptance Criteria
- [x] Create a document in Confluence, similar to the [Q1 metrics page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2051538980/Q1+2022+Baseline+KRs), that includes the same data for Forms Library support requests during the April 21, 2022 - July 21, 2022 time frame.
- [x] The page has been reviewed by the following FLT members:
    - [x] Anish
    - [x] BJ
    - [x] Brittany
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Lauryl
    - [x] Micah
    - [x] Nick
- [x] FLT member feedback has been addressed.

**Comment by biannuz** [comment]
Confluence page published here: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2291236871/Q2+2022+Forms+Library+KRs+April+-+July+2022+Stats+after+updated+documentation

**Comment by laurylzenobi** [comment]
@biannuz reviewed and added comments to strengthen the argument

**Comment by obliviga** [comment]
Looks good to me, I just made a couple of super minor edits regarding grammar and readability.

**Comment by obliviga** [comment]
@taylorkaren, I just reviewed the actual document that should be reviewed. LGTM!
