### ISSUE TITLE
[Q2 Demo Prep] Build the Q2 working demo model form

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#259]
## Task Description
- Build the Q2 working demo model form.
- Use the current multi-page example form as the starting point for this, and build that out to match the Application for Burial Benefits Form, as mocked up on ticket #167 and ticket #227.
- References:
    - [Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2160099329/Model+Form+Design+Mockup+for+Q2+working+demo)
    - [Sketch file](https://www.sketch.com/s/494d1b8a-58ae-4768-9307-0bd7164b2ff9)
    - UXPin prototype to be developed via work on ticket #227
- Note that the Burial form includes an array field (for service history) and a file upload capability. Since we did not build the array or file upload components for the working demo, here's how we should handle those on the model form:
    - Service History: Include the fields as shown on https://www.sketch.com/s/494d1b8a-58ae-4768-9307-0bd7164b2ff9/a/oYPq01x, and include the Add another service period button in a disabled state as shown in Sketch. We can put some text on the page explaining that there is limited functionality in the working demo and only one service history entry is supported at this time.
    - File Upload: Include an Upload button in a disabled state as shown on https://www.sketch.com/s/494d1b8a-58ae-4768-9307-0bd7164b2ff9/a/dlxqaz9. We can put some text on the page explaining that there is limited functionality in the working demo and only one service history entry is supported at this time.

## Considerations
- This is the form we will build with the Q2 Working Demo version of the VA Forms System Core (VAFSC) to prove that the basic form inputs and routing functionality can be used to stand up a basic (unauthenticated experience) form.
- This form will be used as an example of a full form implementation when we do the working demo presentation to application teams in late June, 2022.

## Acceptance Criteria
- [x] Pages have been built according to their tickets
  - [x] #228 intro page
  - [x] #299 claimant information page
  - [x] #300 deceased veteran information page
  - [x] #301 burial page
  - [x] #302 service period page
  - [x] #303 previous names page
  - [x] #304 benefits selection page
  - [x] #305 burial allowance page
  - [x] #306 claimant contact information page
  - [x] #343 plot or interment allowance page
  - [x] #231 review page
- [x] A full form has been built using the Working Demo version of the VA Forms System Core (VAFSC).
- [x] This form matches the desktop and mobile mockups created on ticket #167 and ticket #227.
- [x] A [page has been created](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2226454605/21P-530+Burials+Form+Prototype) in the Forms System Core Architecture section of the FLT Confluence space that describes the model form and includes links to the code for the form as well as the the user facing form itself.
    - [x] Page should note that the Document Upload page ([example](https://preview.uxpin.com/64d3c5baeea35fa18c11add52a41f9227620c74f#/pages/149929274/simulate/sitemap?mode=i)) was not included in the demo form because we did not build the file upload component for the Q2 working demo.
    - [x] Page should note that a new Review Page pattern is in use.
- [x] The page has been reviewed by all members of the FLT:
    - [x] Anish
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick

**Comment by micahchiang** [comment]
Confluence page for burials form - https://vfs.atlassian.net/wiki/spaces/FLT/pages/2226454605/21P-530+Burials+Form+Prototype
