### ISSUE TITLE
Component research part 2

### ISSUE THREAD

**Issue by biannuz** [department-of-veterans-affairs/va-forms-system-core#263]
## Task Description
Conduct primary research to determine:
- [x] What components/form elements do engineers use the most? (e.g. full name, address, etc.)
- [x] In their experience, which components work best/are most reliable?
- [x] Which components are least reliable?

Methodology: A short (5-10 minutes) questionnaire for engineers with experience using the forms library to complete in their own time.

## Acceptance Criteria
- [x] A [page has been created in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2277114009/Component+Survey) that summarizes the research items listed above in the Task Description section.
----------------------------------
Page has been reviewed by:
- [x] Anish
- [x] BJ
- [x] Harshil
- [x] Karen
- [x] Lauren
- [x] Micah
- [x] Nick
-----------------------------------
- [ ] Review feedback has been addressed
-----------------------------------
- [ ] Message Paul Smith with a link to the research page when it is complete. This is the [Slack thread](https://adhoc.slack.com/archives/C9N13SSCQ/p1649446685625099) for the relevant conversation. (Will do this after review & acceptance.)

**Comment by biannuz** [comment]
Questionnaire live here: https://forms.gle/LgJbL4nrXwvJVnmPA

Questionnaire was shared in the VA Slack here: https://dsva.slack.com/archives/CE4304QPK/p1653334152552909

**Comment by taylorkaren** [comment]
[Brittany Slack psot](https://adhoc.slack.com/archives/C02QDMC44RF/p1653408660521889?thread_ts=1653334172.180179&cid=C02QDMC44RF): Frustratingly, I can’t make the survey in Google Forms accessible to users outside the Ad Hoc organization. I’m going to rebuild the survey in Optimal Workshop and re-launch it in the DSVA Slack later today.

**Comment by taylorkaren** [comment]
@biannuz: Chatted about this with Lauryl and Kavitha. If you go into the Settings for the form, in the Response section, there is a toggle that will allow the form to be accessed by people outside the Ad Hoc organization (see below). Flip that toggle and that should allow non-Ad Hoc people to respond.

NOTE: People using a va.gov email address may still be unable to use the form, due to restrictions on the VA side. If our survey population is primarily people working for the contracting organizations on various VFS teams, we should be OK.

![Screen Shot 2022-05-27 at 1.17.57 PM.png](https://images.zenhubusercontent.com/6177f86fa75d95db28de0126/e406674c-a0b2-4e2c-87c7-b15ec384024d)

**Comment by taylorkaren** [comment]
Confluence page is here: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2277114009/Component+Survey.
