### ISSUE TITLE
Rewrite tests for FormRouter, Chapter, and Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#274]
## Description
With the upgrade to react router v6, our FormRouter, Chapter, and Page components have been refactored and the tests need to be updated. 

## Tasks
- [ ] Fix all breaking unit tests for the above mentioned components
- [ ] Remove any tests that are no longer relevant 

## Acceptance Criteria
- [ ] Tests have been updated
- [ ] PR has been merged into main

**Comment by micahchiang** [comment]
Closing because work was completed in #273
