### ISSUE TITLE
[Documentation] Migrate list loop v2 guides to developer docs

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#289]
## Description
[This directory](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/engineering/forms-system) contains some documentation that highlights advanced use cases for the list loop pattern. These should be migrated to the developer docs website. 

## Tasks
- [x] [This list loop v2 guide for add item](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/forms-system/list_loop_v2_add_item.md) should be migrated into the how to section of the updated documentation
- [x] [This list loop v2 guide for contact info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/forms-system/list_loop_v2_contact_info.md) should be migrated into the how to section of the updated documentation
- [x] Once migration is complete for the above 2 documents, update [this readme.md file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/forms-system/readme.md) with a note saying that directory is deprecated and will no longer contain up to date information about the forms system
- [x] Put a Deprecated message on the [VAFS/RJSF Recipes information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/engineering/forms-system) GitHub doc.
- [x] Close [ticket #9070](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9070).
- [x] Check off the bullet point for 9070 on ticket #157.

## Acceptance Criteria
- [x] Guides have been migrated (see doc links in comment below)
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] Move docs from the [Platform Website Drafts space](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980) to the [Developer Docs staging space](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2085355587/VA+Forms+System+Overview).

**Comment by taylorkaren** [comment]
Draft content links:
- VA Forms Library - How to create the contact info Array Data (aka List Loop): https://vfs.atlassian.net/wiki/spaces/PWD/pages/2196897821/VA+Forms+Library+-+How+to+create+the+contact+info+Array+Data+aka+List+Loop: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2194080146/VA+Forms+Library+-+How+to+use+Add+item+link+in+Array+Data+aka+List+Loop
- VA Forms Library - How to use "Add item" link in Array Data (aka List Loop)

**Comment by sdk-irl** [comment]
@micahchiang just a reminder I get a 404 when I click on ticket [9070](https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/9070), so I can't close that, but when it is done, I will check off the last two items

**Comment by micahchiang** [comment]
@sdk-irl - Sorry, the link I added above was incorrect. [This is the correct 9070](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9070) if you are interested, but I've gone ahead and closed it. I've also checked of the checkbox in #157. Thanks for getting this done!

**Comment by taylorkaren** [comment]
@micahchiang and @sdk-irl: I don't see any deprecated messages on the https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/engineering/forms-system and https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/forms-system/readme.md pages. Were those tasks checked off in error or is there a pending update to these pages that has not been committed?

**Comment by micahchiang** [comment]
Added deprecation to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/forms-system/readme.md which serves both of the links you mentioned @taylorkaren

**Comment by sdk-irl** [comment]
@micahchiang I had created a PR with a note for depracation, but it didn't get merged in (and was not as obvious as your note anyway). Didn't know we could edit master. I'll find the PR and close it so it doesn't get merged in and overwrite your note

**Comment by micahchiang** [comment]
LGTM.

**Comment by taylorkaren** [comment]
Should get deployed on Thursday, 5/26.

**Comment by taylorkaren** [comment]
Pages posted to the live site on 5/26/22:
- https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library---How-to-create-the-contact-info-Array-Data-(aka-List-Loop).2196897821.html
- https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library---How-to-use-%22Add-item%22-link-in-Array-Data-(aka-List-Loop).2194080146.html
