### ISSUE TITLE
[Documentation] Reference Getting Started with VA.gov Forms

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#290]
## Description
[Getting Started with VA.gov Forms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md) serves as an excellent introduction into the process behind digitizing a paper form and hosting it on VA.gov. While this document doesn't need to be migrated, it'd be beneficial to reference and link to it from the developer docs. 

## Tasks
- [x] Add a link to the Getting Started with VA.gov Forms document that points to the developer docs
- [x] Add a brief note about the document and link to it from the Welcome section of the [VA Forms Library Overview page](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library-Overview.2085355587.html). Content could be something like: 

_"This is technical documentation meant to serve as a reference for software engineers working on the platform. If you're interested in reading more about the initial process of moving a paper form online, and the content design behind it, check out [Getting Started with VA.gov Forms](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library-Overview.2085355587.html)"_

NOTE: We may want to link to the [Patterns | Forms page on design.va.gov](https://design.va.gov/patterns/forms/) that is generated from the [Getting Started with VA.gov Forms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md) GitHub page, rather than linking directly to the GitHub page.

## Acceptance Criteria
- [x] Tasks have been completed
- [x] Bullet point for Getting Started with VA.gov Forms has been checked off on #157

**Comment by taylorkaren** [comment]
I just updated the bullet point about this on ticket #157, from something I learned in the DST Office Hours call. Please take a look at the updated bullet point on #157 and update this ticket, if needed.

**Comment by micahchiang** [comment]
Completed and closed
