### ISSUE TITLE
[Q2 Demo Prep] Q2 Working Demo Product Summary Doc

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#292]
## Task Description
Create a page in the Product Docs section of the FLT Confluence space that details what is included in the Q2 2022 version of the new VA Forms System Core application. This page will be referenced in Q2 Working Demo presentation materials.

## Considerations
This page should include the following:
- "This working demo will" bullet points from the [Roadmap page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/1992589392/Roadmap+Current)

-  A list of the components that are available to use (get list from https://vfs.atlassian.net/wiki/spaces/FLT/pages/2142863361/VAFSC+Web+Components+-+Q2+Tracking)

- A reference to the [Core Design doc page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2025029667/VA+Forms+System+Core+Design+Document+WIP) for full design details. This page will be updated via work on ticket #293

- Detail the differences between the current Forms Library and the VAFSC working demo:
    - Table comparison, note pain points addressed by the new VAFSC approach
    - No longer defining a form using Form config, now defining via React components
    ⁃ New review page pattern
        ⁃ Summarize research findings and why this new pattern
        ⁃ This is a first cut at a new review page pattern, will refine in Q3

- What’s next?
    ⁃ **_TBD - consult with Matt about how he wants to frame this_**

## Acceptance Criteria
- [x] A [Q2 Working Demo Product Summary page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2208432137/Draft+WIP+VA+Forms+System+Core+Q2+2022+Working+Demo+Product+Summary) has been created in the Product Docs section of the FLT Confluence space.
- [x] This page includes all of the content listed above in the Considerations section.
- [x] The page has been reviewed by all members of the FLT:
    - [x] Anish
    - [x] BJ
    - [x] Brittany
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick

**Comment by taylorkaren** [comment]
Draft page established here: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2208432137/KT+WIP+VA+Forms+System+Core+VAFSC+Q2+Working+Demo+Product+Summary.
