### ISSUE TITLE
[Documentation] Migrate Static Page Widget Section to depo documentation site

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#297]
## Description
[The Save In Progress Page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/save-in-progress/) of the old documentation website contains a section about static page widgets. While this isn't strictly related to the forms library, this section should be migrated into its own how-to guide on the [depo documentation site](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library-Overview.2085355587.html) since the page it lives on is getting deprecated. 

## Tasks
- [ ] Migrate the static page section of [The Save In Progress Page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/save-in-progress/) to the [how-to guide section](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library---How-Tos.2162622465.html) of the depo website

## Acceptance Criteria
- [x] Tasks have been completed
- [ ] FLT members have reviewed and provided feedback on [the draft content:](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2193457291/VA+Forms+Library+-+How+to+set+up+static+widgets)
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [ ] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [ ] Feedback has been addressed.

**Comment by taylorkaren** [comment]
Page location on the Developer Docs staging site: https://vfs.atlassian.net/wiki/spaces/pilot/pages/2193457291/VA+Forms+Library+-+How+to+set+up+static+widgets.

**Comment by taylorkaren** [comment]
Page has been deployed to Prod (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library---How-to-set-up-static-widgets.2193457291.html) - closing ticket.

**Comment by taylorkaren** [comment]
Page has been deployed to Prod (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library---How-to-set-up-static-widgets.2193457291.html) - closing ticket.

**Comment by taylorkaren** [comment]
Page has been deployed to Prod (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library---How-to-set-up-static-widgets.2193457291.html) - closing ticket.

**Comment by taylorkaren** [comment]
Page has been deployed to Prod (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-Library---How-to-set-up-static-widgets.2193457291.html) - closing ticket.
