### ISSUE TITLE
[Routing / Demo Prep] Progress Bar and Step components

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#298]
## Description
As a user, I want visual feedback that lets me know I am progressing through the form, and that clearly communicates each step I am on.

## Considerations
<details><summary>Current progress bar and step component UI</summary>

![Screen Shot 2022-05-09 at 9.36.37 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/09e32c3c-5e56-4d34-b462-e6441d561fa3)
![Screen Shot 2022-05-09 at 9.36.46 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/505cdcec-d9fb-4c7e-b693-290624d1c606)
</details>

- [va-segmented-progress-bar web component](https://design.va.gov/storybook/?path=/docs/components-va-segmented-progress-bar--default)
- #249 deals with an a11y issue in the current forms library progress bar. The suggested fix is to remove the progress bar from the tab order. We may want to do the same here to avoid a similar issue in VAFSC
- Progress bar and step component should both update when clicking forwards and backwards through a form.
- Step Component may make sense as its own component, may not, implementation left up to whoever is working on the ticket. Needs to update step name when moving back and forth.
- May be best suited to live in the `FormRouter` component, looking something like: 
```
export default function FormRouter(props: RouterProps): JSX.Element {
  const initialValues = props.formData;

  return (
    <BrowserRouter basename={props.basename}>
      {props?.title && (
        <FormTitle title={props.title} subTitle={props?.subtitle} />
      )}
      <SegmentedProgressBar />
      <StepComponent />
       // ... Formik implementation
      <FormFooter />
    </BrowserRouter>
  );
}
```

## Tasks
- [x] Create the progress bar component using the va-segmented-progress-bar web component
- [x] Create the step component
- [x] write tests for each

## Acceptance Criteria
- [ ] Tasks have been completed
- [ ] PR has been approved and merged
