### ISSUE TITLE
[Q2 Demo Prep] Build Claimant Information Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#299]
## Description
The first page of the burials form asks for Claimant information which includes full name and a radio group. 

<details><summary>UI</summary>

![Screen Shot 2022-05-09 at 11.02.28 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/784b95fe-108a-4e6b-ad22-3b40740cb120)
</details>

## Considerations
- url is `/claimant-information`
- Previous page: Form Introduction page
- Next page: `/veteran-information`

## Tasks
- [ ] Build the claimant information page according to the attached UI
- [ ] Add unit tests that test the dom for form fields

## Acceptance Criteria
- [x] Tasks complete
- [x] PR has been merged into main
- [ ] Check off the checkbox in #259 to mark the page as complete
