### ISSUE TITLE
[Q2 Demo Prep] Build Veteran Information Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#300]
## Description
The burials form asks for information pertaining to the deceased veteran in question. Information asked for is full name, SSN, VA file number, date of birth, and place of birth. 

<details><summary>Veteran Information UI</summary>

![Screen Shot 2022-05-09 at 11.19.26 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/c3faf2d9-ff02-4f38-b6b9-3e021041ccde)
</details>

## Considerations
- form can be filled out at staging.va.gov/burials-and-memorials/application/530
- SSN and VA file number are conditionally required. At least one of them is needed, but not both. 
- Previous page: `/claimant-information`
- Next page: `/veteran-information/burial`

## Tasks
- [ ] Build veteran information page
- [ ] add unit tests for form fields 

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
- [ ] Check off the checkbox in #259 to mark page as complete

**Comment by bjmccotter7192** [comment]
PR: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/347
