### ISSUE TITLE
[Q2 Demo Prep] Build Burial Information Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#301]
## Description
The burial information page asks for: 
- Date of death
- Date of burial
- Where death occurred

<details><summary>Burial Page UI</summary>

![Screen Shot 2022-05-09 at 11.34.54 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/b7ff18bb-659d-431a-a22e-e30820e7f9fc)
![Screen Shot 2022-05-09 at 11.35.49 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/d3a9d11f-c106-4950-b90d-be6acdf1381b)
![Screen Shot 2022-05-09 at 11.36.11 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/665595f2-ab20-4c65-8ec9-92f1de907e28)
![Screen Shot 2022-05-09 at 11.44.02 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/44c55f51-f9ed-4bc6-9395-3690a295d295)
</details>

## Considerations
- Date of burial cannot be before date of death. See UI for error messaging details
- If date of burial is more than 2 years ago from today's date, an informational message appears below date field. See UI for details
- [Current date validation for this page](https://github.com/department-of-veterans-affairs/vets-website/blob/9ab4ce64d40646fd0934095919715dc71e287193/src/applications/burials/validation.js#L4). It uses moment, which we shouldn't use because it's officially deprecated, but we should be able to do something similar. Micah suggests using "date-fns": "^2.24.0",  "date-fns-tz": "^1.1.1", - drop this into our package and use this to validate dates.
- if `other` is selected in the radio group for location of death, then a text field renders below asking for more details. See UI
- Page url: `/veteran-information/burial`
- Previous page: `/veteran-information`
- Next page: `/military-history/service-periods`

## Tasks
- [ ] Build burial page according to UI spec
- [ ] add unit tests

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
- [ ] Check off the checkbox on #259 to mark page as complete
