### ISSUE TITLE
[Q2 Demo Prep] Build military service history page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#302]
## Description
The military service history page asks for the following fields: 
- Service start date
- Service end date
- Branch of service
- Rank
- Service number
- Place of entry
- Place of separation

<details><summary>Service History UI </summary>

![Screen Shot 2022-05-09 at 11.53.09 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/cbdeb5e4-b958-4945-8d7a-c76b526e9409)
![Screen Shot 2022-05-09 at 11.54.12 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/f0a4e666-e7e8-433f-9b58-58f2ae2cf5e3)
</details>

## Considerations
- None of the fields are required
- Part of the Military History Chapter as evidenced by its URL
- End date cannot be before start date. See UI for error messaging
- _**This is technically an array field, but for Q2 we will not support array fields. The `add another Service Period` button can remain in a disabled state**_
- Page url: `/military-history/service-periods`
- Previous page: `/veteran-information/burial`
- Next page: `/military-history/previous-names`

## Tasks
- [ ] Build service periods page
- [ ] add unit tests

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
- [ ] Check off the checkbox on #259 to mark page as complete

**Comment by bjmccotter7192** [comment]
https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/353
