### ISSUE TITLE
[Q2 Demo Prep] Build Previous Names Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#303]
## Description
The previous names page contains a single yes/no question asking if the veteran served under a different name. If `no`, then the page is complete. If `yes`, then a full name field is rendered underneath the original yes/no question. 

<details><summary>Previous Names UI</summary>

![Screen Shot 2022-05-09 at 12.28.18 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/9262f2c3-3af7-46ab-8f6c-13c2b0472da9)
![Screen Shot 2022-05-09 at 12.28.28 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/0f2c43ad-7d35-45cf-b7ed-6094121d0153)
</details>

## Considerations
- The conditional full name field is an array field similar to service periods. For now, we will handle it the same. `Add another name` button will remain disabled and we will only allow the entry of a single previous name
- Part of the Military History Chapter as evidenced by its URL
- Blue border should come from a utility class on design.va.gov
- page url: `/military-history/previous-names`
- Previous page: `/military-history/service-periods`
- Next page: `/benefits/selection`

## Tasks
- [ ] Build previous names page
- [ ] Write unit tests

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
- [ ] Check off the checkbox on #259 to mark page as complete
