### ISSUE TITLE
[Q2 Demo Prep] Build Benefits Selection Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#304]
## Description 
The benefits selection page asks a single question about expenses incurred for the Veteran's burial. It uses a checkbox group. 

<details><summary>Benefits Selection UI</summary>

![Screen Shot 2022-05-09 at 12.50.35 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/4c085aba-369f-4608-9461-8ad2f7234c3b)
![Screen Shot 2022-05-09 at 12.50.49 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/6ac3765a-e295-4e66-935a-5f2f54306c4b)
![Screen Shot 2022-05-09 at 12.51.00 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/7690ee30-2891-47cd-b162-b066164f158e)
</details>

## Considerations
- Part of the Benefits chapter as evidenced by the url
- If the third checkbox option is selected, then a conditional field is rendered. See UI for details
- Conditionally rendered text field should have validation - make sure it is a numerical dollar amount
- Page url: `/benefits/selection`
- Previous page: `/military-history/previous-names`
- Next page: `/benefits/burial-allowance`

## Tasks
- [ ] Build benefits selection page
- [ ] write unit tests

## Acceptance Criteria 
- [ ] Tasks are complete
- [ ] PR has been merged into main
- [ ] Check off the checkbox on #259 to mark page as complete
