### ISSUE TITLE
[Q2 Demo Prep] Build Burial Allowance Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#305]
## Description
The burial allowance page contains two questions using radio groups:
![Screen Shot 2022-05-09 at 1.14.26 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/8d63132d-c770-4333-a5e0-6e9de0a625a0)

## Considerations
- Part of the benefits chapter as evidenced by the URL
- Page url: `/benefits/burial-allowance`
- Previous page: `/benefits/selection`
- Next page: `/benefits/plot-allowance`

## Tasks
- [ ] Build the burials allowance page
- [ ] write unit tests

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
- [ ] Check off the checkbox on #259 to mark page as complete
