### ISSUE TITLE
[Q2 Demo Prep] Build Claimant Contact Information Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#306]
## Description
The claimant contact information page asks for the following fields:
- Address
- email
- phone number

<details><summary>Claimant Contact Information UI</summary>

![Screen Shot 2022-05-09 at 1.34.56 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/e96929b2-2744-4a88-bfd4-40accc0af407)
![Screen Shot 2022-05-09 at 1.40.55 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/26ef5c31-aebc-40d3-b6af-32bdeaae7ed0)
</details>

## Considerations
- Address is missing military checkbox, but this is an older form so we should still use our new address widget here which will handle the military address checkbox
- phone and email are not required
- Page url: `/claimant-contact-information`
- Previous page: `/benefits/plot-allowance`
- Next page: `/review-and-submit`

## Tasks
- [ ] Build claimant information page
- [ ] write unit tests

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
- [ ] Check off the checkbox on #259 to mark page as complete
