### ISSUE TITLE
[Q2 Demo Prep] Adjust Form Wide CSS classes

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#307]
## Description
Forms on VA.gov are typically wrapped in some universal css utility classes provided by the design system to ensure a consistent UI experience. These need to be added to VAFSC. 

## Considerations
- FormRouter needs to return its usual elements wrapped in some markup to include the DS utility classes. This may look something like this: 

```
export default function FormRouter(props: RouterProps): JSX.Element {
  const initialValues = props.formData;

  return (
 <div className="row">
  <div className="usa-width-two-thirds medium-8 columns">
    <BrowserRouter basename={props.basename}>
      {props?.title && (
        <FormTitle title={props.title} subTitle={props?.subtitle} />
      )}
      <Formik
        initialValues={initialValues}
        onSubmit={(values, actions) => {
          actions.setSubmitting(true);
        }}
      >
        <Routes>{props.children}</Routes>
      </Formik>
      <FormFooter />
    </BrowserRouter>
  </div>
 </div>
  );
}
```

## Tasks
- [ ] Add css utility classes to FormRouter

## Acceptance Criteria
- [ ] Classes have been added
- [ ] PR has been merged into main
