### ISSUE TITLE
[JSON Schema Support] Provide an optional transformForSubmit prop to use at submission

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#312]
## Description
Occasionally, at time of form submission, data may need to be composed a certain way to conform to the schema structure vets-api is expecting. This is currently done with a property called `transformForSubmit`. VAFSC should offer the same functionality. 

## Considerations
- [current default transformForSubmit](https://github.com/department-of-veterans-affairs/vets-website/blob/a94ba75c0deee25f297e3a20a9f16b6a7e7f128f/src/platform/forms-system/src/js/helpers.js#L638) that runs if one isn't provided. It removes unused data from inactive pages and runs a `JSON.stringify` on the formData.
- [transformForSubmit example](https://github.com/department-of-veterans-affairs/vets-website/blob/f7ea62a9ed4c917df142ebaf06fd613b22419501/src/applications/appeals/10182/config/submit-transformer.js#L10)
- This would be run when a user clicks `submit form` on the review and submit page
- May be passed into the `FormRouter` component optionally. 

## Tasks
- [ ] Create a `transformForSubmit` hook that runs at submission which allows users to reshape the payload should they desire to.
- [ ] Create a way to validate form values against a schema at time of submission
- [ ] Add unit tests
- [ ] Add documentation around what `transformForSubmit` does

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
