### ISSUE TITLE
Prototype Development for Review Page Research Round 2

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#323]
## Task Description
 **Make a copy of the UXPin file** developed for the working demo review page on ticket #227 and use that as the basis for a full-fledged prototype that will test the following (based on 5/22/20 PO sync call with Matt):
- Desktop and Mobile screens - DONE
- Design A (baseline) Review Page with Edit links at the section level that take you back to the page associated with the section (the more common/tried and true path) (Use the new version of Design #3 created on ticket #227) - DONE
- Design B Review Page with Edit links at the field level that take you back to the page associated with the field, with the page focus anchored on the selected field (Use Design #2 from the first round of research) - DONE
- For both designs, once you are on the form page to make a change:
    - Update information and return directly to the Review Page if no logic change - DONE
    - Update information and be sent through additional pages if updates needed - ~~**_OUR SCENARIO JUST HAS AN ADDITIONAL DATA ENTRY ON THE PREVIOUS NAMES PAGE, IT DOES NOT REQUIRE GOING THROUGH ADDITIONAL PAGES. THE SCENARIO FOR THIS WOULD BE TO SELECT BURIAL ALLOWANCE OR PLOT OR INTERMENT ALLOWANCE ON THE BENEFIT SELECTION PAGE, WHICH WOULD REQUIRE FILLING OUT EITHER THE BURIAL ALLOWANCE OR THE PLOT OR INTERMENT ALLOWANCE PAGE._**~~ - RESOLVED, 6/27/22
    - Can fake the return if we need to - OK ON THIS
- Matt would prefer to build a functional demo and use that as the test with users - can UXPin do what we need it to do for the tests we want to do?
    - Can we anchor to a field when we go back to a page? - YES, DONE.
    - Can we see the data from the selected field on the Review page data on the form page we go back to? - YES, ESSENTIALLY HARD CODED
    - Can we change data in a field on a form page we go back to? - YES, BUT WILL NOT CARRY OVER BACK TO THE REVIEW PAGE
    - Will changed data on a form page field carry over to the Review Page display when we go back? - ONLY FOR THE FIELD WE WILL ASK PEOPLE TO CHANGE; THIS IS ESSENTIALLY HARD CODED
- We need to focus the testing on finding out which design (A or B) is more performant, and having a prototype that is as fully functional as possible will facilitate that. - OK
- Per Matt, **we are not interested in what people say they prefer, it’s how well and how quickly people can complete a task.** - OK

## Considerations
- From the 5/20/22 Design Council meeting: Include a Skip option on the Review page to go directly to the Submit button? - NOT IN THE PROTOTYPE, WILL ADD TO THE WORKING DEMO REVIEW PAGE CONSIDERATIONS (TICKET #231)

## Acceptance Criteria
- [x] We have a UXPin [desktop](https://preview.uxpin.com/97fe1afd9dd5b538d36e48187b4a24133e2a6bed#/pages/150370509/simulate/sitemap) and [mobile](https://preview.uxpin.com/3f788e8c6673bebc0365fd5d08a28347037aa809#/pages/150422609/simulate/sitemap) mockup of all Burial Form pages, including the A and B versions of the Review Page, that we will use for Review Page Research Round 2.
- [x] Check updated prototype in different browsers and on different devices to make sure there is a consistent experience across all form factors.
- [x] Update info in the [Phase Four section on the Model Form Design Mockup for Q2 working demo Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2160099329/Model+Form+Design+Mockup+for+Q2+working+demo#Phase-Four).

**Comment by biannuz** [comment]
UXPin Mobile prototype works on my Android mobile device.

**Comment by taylorkaren** [comment]
Eric has made the updates to the complex scenario discussed in the 6/17/22 review meeting:
![Screen Shot 2022-06-22 at 1.27.59 PM.png](https://images.zenhubusercontent.com/6177f86fa75d95db28de0126/c257bf77-0f15-4593-bc66-95b77f0cae56).

Confirm with Brittany that she has reviewed the updates and confirmed they match the paths she will take during the interviews.
