### ISSUE TITLE
Present Review Page Research Findings

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#324]
## Task Description
Present the findings from the May, 2022, Review Page Research at the Design Council meeting on 5/20/22 and the Platform Office Hours call on 5/31/22.

## Considerations
- Use the same slide deck format as when we presented the [Forms Library Discovery Research readout](https://docs.google.com/presentation/d/1zEQgcIH9vYF5uejgCdBaOhBPMQjNr7ZQwkyV8HhYS64/edit#slide=id.g892adcb623_0_141)
- Focus on the open sections/accordions result for the presentation.

## Acceptance Criteria
- [x] Slide deck has been created for a Review Page Research readout using the same slide deck format as when we presented the [Forms Library Discovery Research readout](https://docs.google.com/presentation/d/1zEQgcIH9vYF5uejgCdBaOhBPMQjNr7ZQwkyV8HhYS64/edit#slide=id.g892adcb623_0_141).
- [x] A Confluence page version of the slide deck has been created in the [Research section of the FLT Confluence space](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2149548058/Research).
    - [x] The Confluence page follows the same format as the [Forms Library Team Early Research Findings page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2069495835/Forms+Library+Team+FLT+Early+Research+Findings)
- [x] Presentation of the the findings has taken place in the Design Council meeting on 5/20/22.
- [x] Presentation of the findings has taken place in the Platform Office Hours call on 5/31/22. 
    - [x] Add link to materials on the [Agenda page](https://vfs.atlassian.net/wiki/spaces/AP/pages/1951858742/Office+Hours+Agendas+and+Notes#5/31/22).

**Comment by taylorkaren** [comment]
Slide deck: https://docs.google.com/presentation/d/1q4lGCE7F16o9qOD_xs2pD673HdliQxKezAYlA4FOAuI/edit#slide=id.g12c32882855_0_413.
