### ISSUE TITLE
Planning and materials development for Review Page Research Round 2

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#332]
## Task Description
- Create the planning materials for Review Page research Round 2 with Veterans. 
- Coordinate with Perigean to book interviewees (time frame for research sessions is approximately mid-June -> mid-July)

## Considerations
- This round of research will use the revised prototype developed via work on ticket #323.
- From 5/27/22 PO Sync call: To follow up on some of the issues raised about the number of edit links and the amount of noise in the edit by field pattern, can we include people with limited vision or using magnification on their screen?
    - There is a concern about the line length out to the Edit link for these people - do they even see it?

## Acceptance Criteria
- [x] A Review Page Round 2 research plan is detailed on a page in [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/pst-forms-library/research/review-page-round-two).
    - [x] The research plan follows standard VA guidelines for doing research with Veterans.
    - [x] The research plan includes links to the UXPin Prototype that will be used for testing with Veterans.
- [x] A conversation guide for the research sessions is detailed on a page in [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/pst-forms-library/research/review-page-round-two).
- [x] Contact Perigean (with Lauryl’s assistance, if needed) with above 2 artifacts and a target participant demographics to book interviews with Veterans
    - [x] Request a note-taker from Perigean
- [x] A Confluence page is included in the [Review Page Research section of the FLT Confluence space](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2179399822/Review+Page+Research) that provides a summary of the research to be done and links to the relevant documents in GitHub.

**Comment by taylorkaren** [comment]
Notes for preparing the research materials from Kavitha to Brittany: https://docs.google.com/document/d/1dU68foeoiz_8LLbW5c482jeuVul2CofHDdeqKrmef44/edit

**Comment by taylorkaren** [comment]
Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/pst-forms-library/research/review-page-round-two/round-2-research-plan.md
Conversation guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/pst-forms-library/research/review-page-round-two/round-2-conversation-guide.md
