### ISSUE TITLE
[Documentation] Remove deprecated client app website documentation on 6/24

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#333]
## Description
[This pull request](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/824) was recently merged to add a deprecation message to the forms documentation on the client application website. The message states that all documentation will be removed on 6/17. 

## Considerations
- Messaging should go out to #vfs-frontend, #vfs-engineers, #vfs-all-teams, and #vfs-platform-support that communicates the upcoming date of removal prior to the actual date. It's probably beneficial to send this messaging out multiple times. 

## Tasks
- [ ] send out messaging a few times in the coming weeks
- [ ] Remove forms documentation from client app site on 6/24

## Acceptance Criteria
- [ ] above tasks have been complete

**Comment by taylorkaren** [comment]
Updated messages in the #vfs-frontend, #vfs-engineers, and #vfs-all-teams channels to note that this change will now take place on 6/24.

**Comment by micahchiang** [comment]
PR merged - https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/843
