### ISSUE TITLE
Fix tests for Text, FullName, Date, and Address form builder components

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/va-forms-system-core#336]
### Description
After upgrading the component library from version 8.3 to 10.3, tests to check formik state are failing.

- Component library version 10.3 allows to use native events instead of custom events.
- In test, input updates the value but as it doesn't emit the event formik is not able to identify the change so value is not updated in formik object.
- [Testing library ](https://testing-library.com/docs/example-react-formik/)suggest to verify formik state while we submit.
- Test cases are currently skipped in Text, FullName, Date, and Address components.

### Tasks
- [ ] Fix all skipped tests for the above mentioned components

## Acceptance Criteria
- [ ] Tests have been updated
- [ ] PR has been merged into main

**Comment by nickjg231** [comment]
PR:
https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/457/files?diff=split&w=1
