### ISSUE TITLE
Fix Required Validation Errors

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#339]
## Description
As a user using the VAFSC demo application, you should only see the validation error classes around form fields when on blur runs on that field and is required.

Currently the form will highlight ALL required fields even if you have not clicked inside of that field.

Need to change the way chain validation is working for the required property of the form fields.

## Considerations
<details>
<summary>Current Required Validation Error</summary>

ON PAGE LOAD
![image.png](https://images.zenhubusercontent.com/6173092fcc30ae88d70929b1/968268e4-7d8e-48a4-9b84-b4a836388d84)

ON BLUR OF FIRST FIELD
![image.png](https://images.zenhubusercontent.com/6173092fcc30ae88d70929b1/95674615-5bdc-45dc-b695-99d3882282b3)
</details>

- Need to have the onBlur trigger the validation function and error css classes
- This snippet shows the current chain validation function: 
```javascript
export const chainValidations = <T>(
  props: FieldProps<T>,
  validations: ValidationFunction<T>[]
): ((value: T) => ValidationFunctionResult<T>) => {
  return (value: T) => {
    // Return the error message from the first validation function that fails.
    const errorMessage = validations
      .map((v) => v(value, props))
      .filter((m) => m)[0];
    if (errorMessage) return errorMessage;

    // None of the built-in validation functions failed; run the validate
    // function passed to the component.
    return props.validate ? props.validate(value) : undefined;
  };
};

export const required = <T>(
  value: T,
  props: FieldProps<T>
): ValidationFunctionResult<T> => {
  if (props.required && !value) {
    const errorMessage =
      typeof props.required === 'string'
        ? props.required
        : getMessage('required.default');
    return errorMessage;
  }

  return props.validate ? props.validate(value) : undefined;
};

export const requiredValue = <T>(
  value: T,
  props: FieldProps<T>
): ValidationFunctionResult<T> => {
  if (props.required && !Object.values(value).find((v: boolean) => v)) {
    const errorMessage =
      typeof props.required === 'string'
        ? props.required
        : getMessage('required.default');
    return errorMessage;
  }

  return props.validate ? props.validate(value) : undefined;
};
```

## Tasks
- [x] Edit required validation functionality to trigger on blur instead of on page load
- [x] Test on example page for edge cases
- [x] write tests for each

## Acceptance Criteria
- [x] Tasks have been completed
- [ ] PR has been approved and merged

**Comment by bjmccotter7192** [comment]
https://images.zenhubusercontent.com/375815514/2201a66b-669b-4e5e-946b-8a40fa78d1a9/chainvalidationerror.mov

**Comment by bjmccotter7192** [comment]
https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/346
