### ISSUE TITLE
[Q2 Demo Prep] Build Plot or Interment Allowance Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#343]
## Description
The burial allowance page asks for information surrounding plot allowance and includes several radio groups and text fields

<details><summary>UI</summary>

![Screen Shot 2022-05-25 at 8.31.43 AM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/19b70292-b899-4916-98bd-bccb1d80f011)
</details>

## Considerations
- Selecting "no" for the first radio group question conditionally renders a question directly below, entitled "Was the Veteran buried in a state Veterans cemetery?"
- Selecting "yes" for the last radio group question conditionally renders a text field below asking for "Amount of government or employer contribution". This text field is not a required field. 
- Page url is `/benefits/plot-allowance`
- Previous url is `/benefits/burial-allowance`
- Next url is `/claimant-contact-information`

## Tasks
- [ ] build the plot or interment allowance page
- [ ] add unit tests for the page

## Acceptance Criteria
- [ ] tasks have been complete
- [ ] PR has been merged into main
