### ISSUE TITLE
Radio group values should be serialized as boolean when option values are boolean

### ISSUE THREAD

**Issue by mlauren** [department-of-veterans-affairs/va-forms-system-core#361]
## Description
RadioGroup component is storing string value in formik state. Once option is selected and navigating back to that page value doesn't persist in UI.

<details><summary>Formik state</summary>

![Screen Shot 2022-06-01 at 12.02.30 PM.png](https://images.zenhubusercontent.com/622a528977968ea0007000f0/f984e996-a330-487b-b0e6-aa9b648cacf7)
</details>
Manually convert strings to booleans inside radio group field: https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/main/src/form-builder/RadioGroup.tsx#L35-L38

## Tasks
- [ ] Add boolean conversion so it stores as type boolean in formik state
- [ ] Add checked if value exist

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
