### ISSUE TITLE
[Bug] Pages should restrict navigation when field validation fails

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#363]
## Description
Pages currently allow a user to navigate forwards and backwards even if field validation fails. We should prevent users from progressing through the form if they haven't filled out valid values for each field on a page. 

## Considerations
Our button for navigating to the next page currently looks like this: 

```
  <button
      className="btn next"
      onClick={(event) => {
        event.preventDefault();
        navigate(props.nextPage as To);
       }}
   >
   {' '}
   Next
  </button>
```

We may be able to conditionally navigate here after successful validation. 

## Tasks
- [ ] Fix validation and navigation
- [ ] add unit tests that test for URL change when attempting to navigate 

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
