### ISSUE TITLE
[RFC] Vets Website React Router upgrade from v3 to v5

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#371]
## Description
Though prior discovery work has been complete for the vets-website react-router upgrade, an RFC should be created and circulated so the work is more visible. The RFC should also be presented to the architectural working group.

## Considerations
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/34572
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/35469
- RFCs are located in [this repo](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/tree/main/rfc)

## Tasks
- [x] Write new RFC for router migration

## Acceptance Criteria
- [x] RFC has been written and a link to the document is included in a comment on this ticket.
- [ ] RFC has been presented at the Architecture Working Group meeting (7/6/22).

**Comment by taylorkaren** [comment]
Doc page: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2223800367/RFC+Upgrade+react-router+from+v3+to+v5.

**Comment by micahchiang** [comment]
Issue created for 6/22 platform architecture working group meeting - https://github.com/department-of-veterans-affairs/va.gov-team/issues/42609

**Comment by taylorkaren** [comment]
Per discussion in standup today: Micah has pushed up a PR with the React Router RFC to the repo that is now publicly available for RFCs: https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/30.

**Comment by micahchiang** [comment]
RFC has been removed from the working group agenda, as the information in it is no longer relevant.
