### ISSUE TITLE
Register the VAFSC on the Console UI

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#380]
## Task Description
Register the VAFSC as an experimental application on the Console UI. This will require a PR and an update to GitHub app permissions.

## Resources
- [Documentation regarding creating catalog-info.yaml files](https://github.com/department-of-veterans-affairs/platform-console-ui/blob/main/docs/catalog/creating-a-catalog-info-file.md)
- [Catalog-info.yaml file for Console UI](https://github.com/department-of-veterans-affairs/platform-console-ui/blob/main/catalog-info.yaml)
- [Backstage’s Documentation on YAML config files](https://backstage.io/docs/features/software-catalog/descriptor-format)
- For assistance with getting repositories connected to the GitHub app for the Console UI, contact Eric Voshall.

## Console UI access and educational materials
- If you are interested in checking out the Console UI, and you have a login.gov account, this is the URL: https://platform-console-ui-utility.vfs.va.gov/.
    - NOTE that you will need to be logged in to VA via the Citrix Access Gateway (CAG) or through the SOCKS proxy for this URL to work.
- Logging into the Platform Console: https://vfs.atlassian.net/wiki/spaces/CUI/pages/2098004015/Logging+into+the+Platform+Console+-+Instructions
- https://vfs.atlassian.net/wiki/spaces/CUI/pages/2192015765/What+is+the+Console+Catalog: This page includes a video and a slide deck that walk through the Console UI screens and talk about what it does.

## Acceptance Criteria
- [x] The VAFSC is registered on the Console UI
- [ ] VAFSC info on the Console UI is complete and correct
- [ ] Links to VAFSC code, documentation, and any other supporting information on the Console UI is complete and correct
- [ ] Link to the VAFSC entry in Console UI is included in the VAFSC Deliverables section of the [Transition Plan page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2264695677/Draft+Transition+Plan+Document).

**Comment by nickjg231** [comment]
PR: 
https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/466

**Comment by taylorkaren** [comment]
Notes doc from the 7/25 meeting: https://vfs.atlassian.net/wiki/spaces/CUI/pages/2286452849/Onboarding+Forms+System+Core
