### ISSUE TITLE
[Q2 Demo Prep] Build form confirmation page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#381]
## Description
As a user, I want visual feedback that my form has been successfully submitted. 

<details><summary>Confirmation page UI</summary>

![Screen Shot 2022-06-08 at 3.15.58 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/0b487ec7-2de7-452d-9324-afa8ee1f32c4)
</details>

## Tasks
- [x] Build confirmation page
- [x] Make sure confirmation page is not included in the progress bar

## Acceptance Criteria
- [ ] tasks have been complete
- [ ] PR has been merged into main

**Comment by nickjg231** [comment]
PR https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/404
