### ISSUE TITLE
(Needs refinement) Field: Additional Info

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#398]
## Description
- Micah will close ticket with a note
- There is no user interaction, just import and use the web component directly.

## Considerations
- New web component info: https://design.va.gov/storybook/?path=/docs/components-va-additional-info--default.

<details><summary>Example UI</summary>
**_ADD_**
</details>

## Tasks
- [ ] Import and use va-additional-info to build the new VAFSC additional info component
- [ ] Write unit tests to handle validation cases

## Acceptance Criteria 
- [ ] Tasks have been completed
- [ ] PR has been merged

**Comment by micahchiang** [comment]
Closing this. There isn't anything that needs to be done within VAFSC to use this, as it just manages static content. If an engineer wishes to incorporate this into one of their form page components, they would just use it inline.
