### ISSUE TITLE
Field: Memorable Date (aka Date with text inputs)

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#400]
## Task Description
- [ ] Wrap the memorable date component in Formik
- [ ] Write unit tests

## Considerations
- Note that the official name for this component is Memorable Date.
- This is available as of version 10.7.0 of the component library (the most current release [as of 7/7/22] is 11.0.0). It is marked Use with Caution until it can go through the staging review process, but it is available.
- Design.va.gov link: https://design.va.gov/components/form/memorable-date.
- Storybook: https://design.va.gov/storybook/?path=/docs/components-va-memorable-date--default
- Final review of this component is part of the Design System Team's work in the 7/7 sprint:
https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/848
- There is also a pending accessibility review - fixes are in review as of 7/26/22: https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/844
- Memorable date accessibility fixes going in 7/26, then staging review and should be good to go. There may be some minor adjustments from staging review over the next week or two.

## Acceptance Criteria
- [ ] Tasks have been completed
- [ ] PR has been merged into main

**Comment by micahchiang** [comment]
PR here - https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/502
