### ISSUE TITLE
[Forms System] Q3 2022 Initiative: Prepare to transition Forms Library Team deliverables and handoffs

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#416]
## Problem Statement 
_There is a potential for a contract transition to take place in mid-September, 2022, that will require the Forms Library Team to transition the work done to date on the new VA Forms System Core (VAFSC) and hand off ongoing support work for the current Forms Library._

How might the Forms Library Team plan for a smooth transitions, should it be needed, and also plan for continuing to work on all things forms should the transition not be needed?

## Hypothesis or Bet
The hypothesis/bet for this initiative is that by identifying at the beginning of Q3 the VAFSC deliverables and current Forms Library handoffs that would be needed in a transition scenario, we will be able to work towards having those items in a good state to transition as of September 1, 2022.

See the Q3 FLT Roadmap Brainstorm Mural board for details on [VAFSC Deliverables](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1654695562689/94b4e3e24ba1f83ef7baf4ba5d32959e6ff673a7?wid=0-1655297116433) and [current Forms Library Handoffs](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1654695562689/94b4e3e24ba1f83ef7baf4ba5d32959e6ff673a7?wid=0-1655297369473). 

Definitions:
- VAFSC Deliverables: VAFSC code and artifacts that are in a known state and could be picked up at the time of transition or at a later time to continue work on the system.
- Current Forms Library Handoffs: Ongoing activities for the current Forms Library that would need to be assumed at the time of transition so that there is no gap in providing support for this system. 

## We will know we're done when... ("Definition of Done")
- A transition is needed **AND** the VAFSC Deliverable and current Forms Library Handoff items on the [Q3 FLT Roadmap Brainstorm Mural board](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1654695562689/94b4e3e24ba1f83ef7baf4ba5d32959e6ff673a7?sender=u7b7ab34685f00706a24a6128) have been transitioned to the designated team(s) who will be taking over the work. 

## Known Blockers/Dependencies 
- This work is dependent on the need for a transition of work to take place prior to the September 11, 2022, Spike team contract expiration. If a transition does not need to take place, this initiative will not be applicable.

## Projected Launch Date
- Should a transition be needed, work should be completed by September 9, 2022, as that is the last business day prior to the September 11, 2022, Spike team contract expiration.

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platforminitiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by raywangoctova** [comment]
@humancompanion-usds Can you add/tag Q3 FY22 to the milestone for this issue? This is required by Jeff for the DE product board.

**Comment by humancompanion-usds** [comment]
Transition to the Design System Team is complete.
