### ISSUE TITLE
[Forms System] Q3 2022 Initiative: Pilot the working demo version of the VA Forms System Core (VAFSC)

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#417]
## Problem Statement 
_Smooth and standardized VFS development_ isn’t being achieved today because of a _complex, inflexible, and poorly documented forms system for VFS front end designers and engineers_ which results in _complexity and workarounds in the VFS development process and inconsistent UX for users._

How might we make it possible for any VFS team working on the platform to easily spin up and build forms that provide a consistent veteran user experience across the VA.gov site?

## Hypothesis or Bet
The Q3 hypothesis/bet is that piloting the working demo version of the VA Forms System Core (VAFSC) will provide the means for the Forms Library Team to gather feedback on the real world experience of using this initial version of the  VAFSC to build forms. We anticipate that pilot activities may take one of two approaches:
-  Working on an ongoing basis during July and August 2022 with a team that has a form to build and time in their schedule to try building some or all of the form using the VAFSC.
- Holding one-off walkthrough/Q&A sessions during July and August 2022 with teams that are interested in the new system but not actively building a form at this time.

Anticipated outcomes of the pilot activities to help guide successive phases of the VAFSC buildout:
- Usability feedback: What works well and what doesn't work so well for front end engineers when they try to build a form using the working demo.
- Suggestions for improving the existing working demo functionality.
- Suggestions for adding capabilities to the existing working demo functionality.
Note that this initiative is focused on being a learning experience, not a delivery experience. There is no expectation that a form using the new VAFSC system will be put into production as part of the pilot activities.

## We will know we're done when... ("Definition of Done")
- We have worked with 3-4 teams using one of the pilot approaches listed above during the July - August 2022 time frame.
- We have a summary document of pilot activities and findings to use as an input for planning successive phases of the VAFSC buildout.
- Code for the VAFSC Working Demo current state is included in a branch (not in production, as the React Router upgrade to V6 is a dependency for going to production).

## Known Blockers/Dependencies 
- No known blockers or dependencies as of 6/22/22.

## Projected Launch Date
- The pilot activities and summary document are completed on or about September 1, 2022 (ending at the 2/3 mark during the quarter to allow time for a potential transition of work at the beginning of September).

### Guidance (delete before posting)

_This checklist is intended to be used to help answer, "is my Platform initiative ready for launch?". All of the items in this checklist should be completed, with artifacts linked---or have a brief explanation of why they've been skipped---before launching a given Platforminitiative. All links or explanations can be provided in **Required Artifacts** sections. The items that can be skipped are marked as such._

_Keep in mind the distinction between **Product** and **Initiative** --- each Product needs specific supporting documentation, but Initiatives to improve existing Products should reuse existing documentation for that Product.  [VSP Product Terminology](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-terminology.md) for details._

### ... tested?

- [ ] Usability test (_TODO: link_) has been performed, to validate that new changes enable users to do what was intended and that these changes don't worsen quality elsewhere. If usability test isn't relevant for this change, document the reason for skipping it.
    - [ ] ... and issues discovered in usability testing have been addressed.
    * _Note on skipping: metrics that show the impact of before/after can be a substitute for usability testing._
- [ ] End-to-end [manual QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md) or [UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/what-is-uat.md) is complete, to validate there are no high-severity issues before launching
- [ ] _(if applicable)_ New functionality has thorough, automated tests running in CI/CD

### ... documented?

- [ ] New documentation is written pursuant to our [documentation style guide](https://vfs.atlassian.net/wiki/spaces/AP/pages/622264362/Style+guide)
- [ ] Product is included in the [List of VSP Products](https://docs.google.com/spreadsheets/d/1Fn2lD419WE3sTZJtN2Ensrjqaz0jH3WvLaBtn812Wjo/edit#gid=0)
    * _List the existing product that this initiative fits within, or add a new product to this list._
- [ ] Internal-facing: there's a [Product Outline](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/1924628490/Product+Outline+Template)
- [ ] External-facing: a [User Guide on Platform Website](https://vfs.atlassian.net/wiki/spaces/AP/pages/1477017691/Platform+website+guidelines) exists for this product/feature tool
- [ ] _(if applicable)_ Post to [#vsp-service-design](https://dsva.slack.com/channels/vsp-service-design) for external communication about this change (e.g. customer-facing meetings)

### ... measurable

- [ ] _(if applicable)_ This change has clearly-defined success metrics, with instrumentation of those analytics where possible, or a reason documented for skipping it.
    * For help, see: [Analytics team](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guide.1586823275.html)
- [ ] This change has an accompanying [VSP Initiative Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new/choose).

### When you're ready to launch...
- [ ] Conduct a [go/no-go] (https://vfs.atlassian.net/wiki/spaces/AP/pages/1670938648/Platform+Crew+Office+Hours#Go%2FNo-Go) when you're almost ready to launch. 

### Documentation
* **`PRODUCT_NAME`**: _directory name used for your product documentation_
* **Product Outline**: _link to Product Outline_
* **User Guide**: _link to User Guide_

### Testing

* **Usability test**: _link to GitHub issue, or provide reason for skipping_
* **Manual QA**: _link to GitHub issue or documented results_
* **Automated tests**: _link to tests, or "N/A"_

### Measurement

* **Success metrics**: _link to where success metrics are measured, or where they're defined (Product Outline is OK), or provide reason for skipping_
* **Release plan**: _link to Release Plan ticket_

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic
- [ ] Add this initiative to the [Digital Experience Product Board](https://github.com/orgs/department-of-veterans-affairs/projects/306?card_filter_query=label%3Acrew-platform) using [these instructions](https://vfs.atlassian.net/wiki/spaces/AP/pages/2120974387/Platform+Initiative+Guidelines+for+Digital+Experience+Product+Board)

**Comment by humancompanion-usds** [comment]
We ended up not being able to identify a product team to use the Forms System. We pivoted instead to walking teams through how to use the new Forms System Core (FSC). We held 4 sessions with developers on how to use the FSC. Some of these developers went on to use the FSC.
