### ISSUE TITLE
VAFSC Burials Demo Bug Fix - Privacy Statement and checkbox

### ISSUE THREAD

**Issue by nickjg231** [department-of-veterans-affairs/va-forms-system-core#418]
## Task Description
Moved from ticket #408.
- [x] Add privacy statement and check box to the review page in the Q2 working demo prototype form.
- [x] Per comment below, use the check box **description** to add the link instead of placing it in the label. Note that this is different from how this is currently formatted in Prod and that it is OK to make this alteration.

## Considerations
- Additional information on how we determined what to do for this ticket can be found on https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/961 and in this Slack thread: 
- https://dsva.slack.com/archives/C01DBGX4P45/p1655836583744179

## Acceptance Criteria

- [x] Add the description prop and enable the JSX description option on the CheckboxField component
- [x] Add the privacy policy agreement checkbox to the burial form's review page

**Comment by nickjg231** [comment]
This is currently blocked until the va-checkbox component is allowed to use HTML in the label. There is currently an issue open here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/961
See the slack thread regarding this issue here:
https://dsva.slack.com/archives/C01DBGX4P45/p1655836583744179

- [ ] Add privacy statement and check box.

**Comment by taylorkaren** [comment]
DST Ticket 961 status as of 7/8/22 DST/FLT sync call:
- Katy is queuing this one up for the next sprint. If DST has time in this sprint, someone can get started on it. 
- Carol will work with Sean Sewell on the Governance team for this ticket.

**Comment by taylorkaren** [comment]
Comment from the DST ticket (https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/961):
Advice from Sean Sewell is to use the check box description to add the link instead of placing it in the label.  Let's look into formatting the link as advised and see if that resolves the problem. Note that this is different from how this is currently formatted in Prod and that it is OK to make this alteration.

**Comment by taylorkaren** [comment]
@nickjg231: To follow up on your comment in standup today about possibly making this a component, there is a ticket (#437) to use the Design System Web component when it becomes available. If using a component is going to be the preferred approach, we may want to hold off on this ticket until that component becomes available.

We will get an update from the Design System Team in tomorrow's sync call about when this component might be available. As of the last sync call on 7/26, it was characterized as a stretch goal for Q3, so it may be some time before it is ready.

**Comment by nickjg231** [comment]
PR: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/514

**Comment by GnatalieH** [comment]
@taylorkaren did you end up changing the copy around so the link is in the description, rather than the checkbox text? @seanasewell and I are working on the Web component design for Privacy Agreement, and this issue came up today. I haven't looped in Content, yet. Wanted to check with your team first. Thanks.

**Comment by taylorkaren** [comment]
@GnatalieH: Yes, we did change to put the link in the description. @bjmccotter7192 and I are researching this as I type so we can get you the reference you are looking for.
