### ISSUE TITLE
React Router 3 --> 5 Upgrade How To Guide

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#425]
## Task Description
When coding is complete for the React Router 3 --> 5 upgrade (ticket #287), put together a "How to Upgrade from React Router Version 3 to Version 5" Confluence page to provide guidance to VFS front end engineers who will be making the code changes for their apps.

## Considerations
- Use the existing Confluence pages that have been written by [RTT](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2071363787/React+Router+Guidelines) and [FLT](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2071363787/React+Router+Guidelines) as a starting point and consolidate them into a single page.
- Decide if this page should live in the FLT Confluence space or the RTT Confluence space and locate it accordingly.

## Acceptance Criteria
- [ ] A "How to Upgrade from React Router Version 3 to Version 5" Confluence page has been created in the FLT or RTT Confluence space.
- [ ] This Confluence page has been reviewed by FLT members:
    - [ ] Anish
    - [ ] BJ
    - [ ] Harshil
    - [ ] Karen
    - [ ] Lauren
    - [ ] Micah
    - [ ] Nick
- [ ] FLT member feedback has been addressed.
- [ ] This Confluence page has been reviewed by the appropriate RTT members. We are specifically looking for feedback from the RTT members about applying this upgrade to non-Forms Library apps to make sure the content is sound.

- [ ] RTT member feedback has been addressed.

**Comment by taylorkaren** [comment]
Not needed - we will not complete the React Router V3 --> V5 upgrade work, per conversion with Matt Dingee in the 7/15/22 PO Sync call.
