### ISSUE TITLE
Replace ProgressButton Component with Component Library Equivalent

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#427]
Same as https://github.com/department-of-veterans-affairs/va.gov-team/issues/30908.

## Description
The `ProgressButton` component that lives in `vets-website/src/platform/form-system` is almost identical to the same button that exists in the component library. To avoid diverging functionality between the two, the component that lives in vets-website should be removed and replaced by the one that lives in the component library. 

## Considerations
- [Comment by Brooks on the issue](https://github.com/department-of-veterans-affairs/vets-website/pull/21490#issuecomment-1169126945)
- [Comment by Brooks highlighting some potential migration issues](https://github.com/department-of-veterans-affairs/vets-website/pull/21490#discussion_r908807027)
- [Existing DST ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30908)

## Tasks
- [ ] Remove and replace `ProgressButton.jsx` with the one from the component library
- [ ] Fix any tests that break 

## Acceptance Criteria
- [ ] Above tasks have been complete
- [ ] PR has been merged

**Comment by taylorkaren** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/30908. Closing this ticket.
