### ISSUE TITLE
(Lauren: add notes, takeaways, and next steps) Focused Walkthrough Session: Adam Whitlock

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#428]
## Task Description
Schedule and participate in a focused walkthrough session with Adam Whitlock about using the VAFSC for profile updates and supporting Yup schemas.

## Considerations
- Record the call
- Take notes on the Confluence page set up for this session: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2249293825/Focused+Walkthrough+Session+Adam+Whitlock
    - This page is a model for pages to create for subsequent walkthrough sessions during Q3, 2022.

## Acceptance Criteria
- [x] Walkthrough session has been completed
- [x] Notes from the session are documented on the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2249293825/Focused+Walkthrough+Session+Adam+Whitlock)
- [x] A link to the session recording is included on the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2249293825/Focused+Walkthrough+Session+Adam+Whitlock)
- [ ] FLT members have reviewed the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2249293825/Focused+Walkthrough+Session+Adam+Whitlock) and added notes, takeaways, and next steps:
    - [x] Anish
    - [x] BJ
    - [x] Brittany
    - [x] Harshil
    - [x] Karen
    - [x] Lauren (watch the video and add notes, takeaways, next steps)
    - [x] Lauryl
    - [x] Micah
    - [x] Nick

**Comment by taylorkaren** [comment]
Sent Slack message to Adam:

Hi Adam -  I wanted to reach out and follow up with you regarding your interest in having a focused walkthrough session with the Forms Library Team about using the VA Forms System Core (VAFSC) for profile updates and supporting Yup schemas.

We would like to schedule something with you during the next sprint period (7/7 - 7/19). If you are still interested, could you provide a few time slots when you would be available during that time?

If there are other team members who would like to attend, please let me know who they are and I will include them on the invite.

If there is anything specific that you want to be sure we cover, please let me know about that as well, so that we can prepare anything in advance that will be helpful to you.

Thank you for your interest in the VAFSC - we look forward to working with you!
