### ISSUE TITLE
Semantic versioning of the VAFSC NPM Package

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#432]
## Task Description
Set up semantic versioning in the va-forms-system-core repository to align the Github Releases with the NPM publish version. This will allow us to have automated publishing when a changed gets merged into the master/main branch.
- Review the [VA Forms System Core (VAFSC) Semantic-Release Idea document in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/1992163490/New+Forms+Library+fka+Formulate+Semantic-Release+Idea).
- Revise as needed to reflect what we will do to apply semantic versioning to the VAFSC package.

## Considerations
- VA VSP Github Token
- VA VSP NPM Token
- Semantic versioning would automatically upgrade package # and publish to NPM (Better in the long run than manually updating the package
- Package version numbering increments based on major version release (x), minor version release (x.xx), and patch (x.xx.xx)

## Tasks
- Do the work listed in the [Things that we will need to complete section of the VA Forms System Core (VAFSC) Semantic-Release Idea document in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/1992163490/VA+Forms+System+Core+VAFSC+Semantic-Release+Idea#Things-that-we-will-need-to-complete%3A)

## Acceptance Criteria
- [x] Semantic versioning has been added to project
- [x] NPM package version gets upgraded with every merge to master
- [ ] FLT members have reviewed and provided feedback:
    - [ ] Anish
    - [ ] BJ
    - [ ] Harshil
    - [ ] Lauren
    - [ ] Micah
    - [ ] Nick

**Comment by taylorkaren** [comment]
@bjmccotter7192 to add a link to the Draft PR he worked on for this.

**Comment by bjmccotter7192** [comment]
[Semantic Versioning Draft PR](https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/477)

**Comment by taylorkaren** [comment]
Ops team ticket blocking this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/45092.
