### ISSUE TITLE
Analysis: VAFSC NPM Package working on Vets Website

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#433]
## Task Description
Research and define what needs to be done to make the VAFSC NPM package work with Vets Website.

## Considerations
- This is a research and analysis task to define what steps would need to be taken to get the VAFSC NPM package working on Vets Website. 
- Steps should include all work that the Forms Library Team (or a successor team) would need to do, in addition to work that would need to be done by other platform teams (either in coordination with the Forms Library Team or on their own; e.g., React Router 6 upgrade).

## Acceptance Criteria
- [ ] A page detailing the steps needed to get the VAFSC NPM package working on Vets Website has been added to the Forms Library Team Confluence space.
- [ ] The page has been reviewed by all engineering and product management members of the FLT:
    - [ ] Anish
    - [ ] BJ
    - [ ] Harshil
    - [ ] Karen
    - [ ] Lauren
    - [ ] Micah
    - [ ] Nick
- [ ] FLT member feedback has been addressed.

**Comment by micahchiang** [comment]
Closing in favor of 258
