### ISSUE TITLE
Document all code and other artifacts for the VAFSC

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#435]
## Task Description
Create a page in the Forms Library Team Confluence space that documents all relevant code and other artifacts for the VAFSC.

## Considerations
- ~~As a start, the page should provide links and explanation text for the items included in the [Transition Support - VAFSC Deliverables section](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1654695562689/94b4e3e24ba1f83ef7baf4ba5d32959e6ff673a7?wid=0-1655297116433) on the Q3 FLT Roadmap Brainstorm board to get items for this list.~~ - DONE, 7/20/22.
- This is the catalog of all things VAFSC, so add links and explanation text for anything else not on the Mural Board that a team picking up the VAFSC work would need to know. - First draft done, 7/21/22.
- ~~Think about doing a Confluence space reorg so that all things current Forms Library and all things VAFSC are consolidated under their own top-level sections.~~ - DONE, 7/21/22
    - ~~And then put links to each of those sections on the Overview page, with some text explaining the two work streams that the team supports.~~ - DONE, 7/21/22
 
## Acceptance Criteria
- [x] [Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2280161283/Draft+VA+Forms+System+Core+VAFSC+Work+Stream) has been created as described in the Considerations section.
- [x] The page has been reviewed by all members of the FLT:
    - [x] Anish
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
- [x] FLT member feedback has been addressed.

**Comment by taylorkaren** [comment]
Draft page started here: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2280161283/Draft+VAFSC+Code+and+Artifacts.

**Comment by taylorkaren** [comment]
7/21/22, finished reorg on the Confluence space structure:
![Screen Shot 2022-07-21 at 10.17.11 AM.png](https://images.zenhubusercontent.com/6177f86fa75d95db28de0126/92707463-e411-413a-bb39-b64fece1b21b).

Also updated the Overview page (https://vfs.atlassian.net/wiki/spaces/FLT/overview) to include links at the top to each of the work stream sections within the space.

**Comment by taylorkaren** [comment]
Updated the https://vfs.atlassian.net/wiki/spaces/FLT/pages/2280161283/Draft+VA+Forms+System+Core+VAFSC+Work+Stream on 8/5/22. Will take another pass on this page in a week or so.

**Comment by micahchiang** [comment]
lgtm! Nothing to add.

**Comment by bjmccotter7192** [comment]
LGTM, left one comment on the React Router V5 -> V6 link.
