### ISSUE TITLE
[Bugfix] Fix conditional page routing

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#442]
## Description
Recent changes to the checkbox group component accidentally broke conditional page routing. Conditional routing needs to be fixed by updating the radio options to include object and children names like so: "breakfast.protien".

## Tasks
- [ ] fix conditional routing

## Acceptance Criteria
- [ ] tasks have been complete
- [ ] PR has been merged into main

**Comment by taylorkaren** [comment]
Lauren fixed this with the page validation ticket (#363).
