### ISSUE TITLE
Validation Functions Documentation

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#445]
## Context
- Suggestion from Matt Dingee in the 6/16 trial run demo call.

## Task Description
- Add a Validation section to the [VA Forms System Core Q2 Working Demo Product Walkthrough page].(https://vfs.atlassian.net/wiki/spaces/FLT/pages/2219966487/VA+Forms+System+Core+Q2+Working+Demo+Product+Walkthrough)
- This section should include:
    - Details about the validation functions that are are available by default in the VAFSC (baked in functions)
    - What to do if you need custom validation
        - Guidelines for writing custom validation
        - How to contact the team for assistance with custom validation 

## Acceptance Criteria
- [ ] The [VA Forms System Core Q2 Working Demo Product Walkthrough page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2219966487/VA+Forms+System+Core+Q2+Working+Demo+Product+Walkthrough) has been updated as described above.
- [ ] FLT members have reviewed the revised [VA Forms System Core Q2 Working Demo Product Walkthrough page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2219966487/VA+Forms+System+Core+Q2+Working+Demo+Product+Walkthrough).
    - [ ] Anish
    - [ ] BJ
    - [ ] Harshil
    - [ ] Karen
    - [ ] Lauren
    - [ ] Micah
    - [ ] Nick
- [ ] FLT member feedback has been addressed.

**Comment by micahchiang** [comment]
Not really blocked by it, but the work in here seems like it'd be included in #460.

**Comment by taylorkaren** [comment]
Work was done on ticket #460.
