### ISSUE TITLE
Initial investigation for Pre-fiil/Save in Progress

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#449]
## Description
Save in Progress (SiP) and prefill are integral parts of the forms system. VAFSC should hook into these APIs so veterans who log into VA.gov have their information preloaded, and users who previously began filling out a form can continue at a later time without starting over. 

## Considerations
- Configuration in vets-website requires very little - setting `prefillEnabled: true` in the `formConfig` object. A similar experience should be available in VAFSC; SiP should require very little configuration. 
- [SiP actions](https://github.com/department-of-veterans-affairs/vets-website/blob/a6eb76b16e503096e9c0b0c7a07754d80a6fa40a/src/platform/forms/save-in-progress/actions.js#L1) which include functions like `fetchInProgressForm`, `removeInProgressForm`, and `saveForm`. 
- [SiP frontend api](https://github.com/department-of-veterans-affairs/vets-website/blob/a6eb76b16e503096e9c0b0c7a07754d80a6fa40a/src/platform/forms/save-in-progress/api.js#L1) which includes `removeFormApi` and `saveFormApi`
- vets-api should require no changes. This should be a frontend only job if at all possible. 

## Tasks
- [x] Evaluate the current SiP and Prefill mechanisms in vets-website and create a confluence document that outlines the work necessary to port that functionality over to VAFSC. This should outline clear tickets that can be created as a follow up

## Acceptance Criteria
- [x] Confluence document has been created
- [x] FLT members have reviewed the [page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2267873306/VAFSC+Prefill+Save+in+Progress+Initial+Discovery) and provided feedback.
    - [x] Anish
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
- [ ] FLT member feedback has been addressed - one comment left as of 8/1/22.

**Comment by micahchiang** [comment]
Confluence doc - https://vfs.atlassian.net/wiki/spaces/FLT/pages/2267873306/VAFSC+Prefill+Save+in+Progress+Initial+Discovery

**Comment by bjmccotter7192** [comment]
Nice work!

**Comment by obliviga** [comment]
Looks good to me, just fixed a super minor type in one of the code snippets.

**Comment by micahchiang** [comment]
Comment addressed, closing
