### ISSUE TITLE
(7/28/22) Focused Walkthrough Session: Benefits 2 Team and the Financial Status Report (FSR) form

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#454]
## Task Description
Schedule and participate in a focused walkthrough session with members of the Benefits 2 Team about using the VAFSC for the Financial Status Report (FSR) form.

## Benefits 2 Team Information
- Team is using the forms library quite a bit; the entire online FSR experience is built on it. 
    - For reference, FSR = Financial Status Report - VA Form #5655
- The team will be shifting gears to work on the Financial Status Report around the week of 7/25/22, so that could be great timing for this meeting. 

## Considerations
- Record the call
- Take notes on the Confluence page set up for this session: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2262630401/Focused+Walkthrough+Session+Benefits+Team+2+Financial+Status+Report+FSR+form

## Acceptance Criteria
- [x] Walkthrough session has been completed
- [x] Notes from the session are documented on the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2262630401/Focused+Walkthrough+Session+Benefits+Team+2+Financial+Status+Report+FSR+form)
- [x] A link to the session recording is included on the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2262630401/Focused+Walkthrough+Session+Benefits+Team+2+Financial+Status+Report+FSR+form)
- [ ] FLT members have reviewed the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2262630401/Focused+Walkthrough+Session+Benefits+Team+2+Financial+Status+Report+FSR+form) and added notes, takeaways, and next steps:
    - [x] Anish
    - [x] BJ
    - [x] Brittany
    - [x] Harshil
    - [x] Karen
    - [x] Lauren (watch the video and add notes, takeaways, next steps)
    - [x] Lauryl
    - [x] Micah
    - [x] Nick
