### ISSUE TITLE
Transition Doc: Support FAQs

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#455]
## Task Description
- Create a page in Confluence that compiles information on common types of help requests we have received during our time supporting the current Forms Library and common approaches for diagnosing and resolving those requests. 
- Include a link to the [VA Forms Library Overview page](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview) so that it's easy to find the Forms Library documentation.
- Link to this new page from the [Forms Library Support page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2129920044/Forms+Library+Support).

## Considerations
- This page would be the basis for a handoff discussion with the Design System Team (if a handoff is needed) to help them understand what people ask and how to respond to them. 
- This could be a good task for the engineer on support during the last week or two of August. 

## Acceptance Criteria
- [x] A [Forms Library Support FAQ page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2326528245/Support+FAQs+Document+WIP) has been created in Confluence.
- [x] This new page is linked to from the [Forms Library Support page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2129920044/Forms+Library+Support).
- [x] The page has been reviewed by the following FLT members:
    - [x] Anish
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
- [x] FLT member feedback has been addressed.
- [x] Add links to this doc on the Transition Plan and Forms Library work stream pages (Karen)

**Comment by micahchiang** [comment]
Created a confluence page - https://vfs.atlassian.net/wiki/spaces/FLT/pages/2326528245/Support+FAQs+Document+WIP

**Comment by bjmccotter7192** [comment]
NIce work gathering all those support requests!
