### ISSUE TITLE
New location for Forms Library content on the Platform website

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#458]
## Context
One of the takeaways from our focused walkthrough session with Adam Whitlock ([Notes Page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2249293825/Focused+Walkthrough+Session+Adam+Whitlock+and+Sharon+Kasimow)) was that documentation for the old Forms Library lives several layers down in the platform website structure and may be difficult to find at that level.

## Task Description
- Investigate moving the Forms Library content that is currently at https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview up a level or two so that it is easier to find.
- For example, it might be better located just under Front End Developer Documentation (https://depo-platform-documentation.scrollhelp.site/developer-docs/frontend-developer-documentation).
   - If we choose this location, a blurb about the Forms Library should be added to the https://depo-platform-documentation.scrollhelp.site/developer-docs/frontend-developer-documentation page.

## Acceptance Criteria
- [x] New location for Forms Library documentation has been identified.
- [x] Forms Library documentation has been moved to the new location on the [staging site](https://vfs.atlassian.net/wiki/spaces/pilot/overview?homepageId=582811793): https://vfs.atlassian.net/wiki/spaces/pilot/pages/2085355587/VA+Forms+Library+Overview
- [ ] ~~Any other docs that should be updated at the same time as the Forms Library pages are moved have been updated on the [staging site](https://vfs.atlassian.net/wiki/spaces/pilot/overview?homepageId=582811793).~~ - N/A
- [x] New location for the Forms Library documentation, and any other updated docs, are deployed to the [live site](https://depo-platform-documentation.scrollhelp.site/developer-docs/) during one of the regularly scheduled Tuesday/Thursday platform web site deployments.

**Comment by taylorkaren** [comment]
Change has been implemented:
![Screen Shot 2022-07-27 at 7.31.22 AM.png](https://images.zenhubusercontent.com/6177f86fa75d95db28de0126/d8ed2ee2-5cf8-4e12-87c5-22b47f367889)
