### ISSUE TITLE
Usability study of Forms Library documentation

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#459]
## Context and Purpose
- One of the takeaways from our focused walkthrough session with Adam Whitlock ([Notes Page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2249293825/Focused+Walkthrough+Session+Adam+Whitlock+and+Sharon+Kasimow)) was that it is not well known where documentation for the old Forms Library lives. 
- We have opened ticket #458 to move the documentation location up a level; as a follow-on to that, we'd like to do a "quick and dirty" usability study to find out if the documentation is findable and if it is working well for people who use it. 

## Task Description
- Do a "quick and dirty" usability study on the current Forms Library documentation site.
- Identify 3-5 VFS front end engineers who have used the Forms Library documentation 
   - Probably want people who have only used the [new documentation site](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview) and some people who have used the [old documentation site - now deprecated](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/) AND the [new documentation site](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview).
    - Maybe talk to some of the people from the Discovery tour? Roster is on the [Forms System Discovery Brief page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/1992163522/Forms+System+Discovery+Brief).
- Find out why people consult the Forms Library documentation - what are they trying to do, what question are they trying to answer?
    - Maybe talk to some of the people who have submitted support requests - do they check the docs before posting in the support channel?
 - Find out if they are able to do what they wanted to do or get their question answered after looking at the docs.

## Goals
- Understand when and why VFS front end engineers seek out Forms Library documentation.
- Can they find the documentation, do they know where it is?
- Gauge how well the Forms Library documentation addresses the reasons why VFS front end engineers are looking at the documentation.
- Identify what is useful (and not so useful) with the current Forms Library documentation content, structure, and location.
- Use findings to:
    - Fine tune the current Forms Library documentation content, structure, and/or location.
    - Guide the build out of documentation for the new VAFSC.

## Acceptance Criteria
- [x] Tasks have been completed.
- [x] A page summarizing the research methodology and findings has been created in the [Forms Library | Documentation Analysis section of the FLT Confluence space](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2058584253/Documentation+Analysis).
- [x] The [research findings page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2321973406/Research+Findings) has been reviewed by the following FLT members:
    - [x] Anish
    - [x] BJ
    - [x] Brittany
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Lauryl
    - [x] Micah
    - [x] Nick
- [x] FLT member feedback has been addressed.
- [x] Add link to the findings page to the relevant transition docs (Karen added to [Transition Plan page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2264695677/WIP+Transition+Plan+Document#Forms-Library-Handoffs))

**Comment by laurylzenobi** [comment]
Draft research plan [here](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2301657089/Usability+study+of+Forms+Library+documentation+Research+plan)

**Comment by laurylzenobi** [comment]
[Research findings](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2321973406/Research+Findings)

**Comment by taylorkaren** [comment]
Reviewed and commented on the [Research findings](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2321973406/Research+Findings); created a placeholder ticket (#569) to record the findings recommendations.

**Comment by micahchiang** [comment]
Nothing to add, lgtm!

**Comment by bjmccotter7192** [comment]
Good work on this everyone!
