### ISSUE TITLE
Add form setup and validation information to the Working Demo Product Walkthrough page

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#460]
## Context
One of the takeaways from our focused walkthrough session with Adam Whitlock ([Notes Page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2249293825/Focused+Walkthrough+Session+Adam+Whitlock+and+Sharon+Kasimow)) was that we don't have good directions for someone to build a simple form and add validation to it.

## Task Description
- Flesh out the How to scaffold a form section on the [VA Forms System Core Q2 Working Demo Product Walkthrough page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2219966487/VA+Forms+System+Core+Q2+Working+Demo+Product+Walkthrough#How-to-scaffold-a-form) by adding information on how to set up a simple single-page form and and pass in a custom validation.

## Acceptance Criteria
- [x] The How to scaffold a form section on the [VA Forms System Core Q2 Working Demo Product Walkthrough page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2219966487/VA+Forms+System+Core+Q2+Working+Demo+Product+Walkthrough#How-to-scaffold-a-form) has been updated with information on how to set up a simple single-page form and and pass in a custom validation.
- [x] The updated page has been reviewed by FLT members:
    - [x] Anish
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren 
    - [x] Micah
    - [x] Nick
- [ ] All feedback has been addressed.

**Comment by obliviga** [comment]
LGTM - just made a super minor edit.
