### ISSUE TITLE
VAFSC Feature To Do List

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#463]
## Task Description
- Original request from Katy was to compile a list of VAFSC features that we didn't get to, with some rough prioritization of those features, to be used as a transition document should a transition be needed.
- Also had a request from Matt to do some analysis on what work still needs to be done on the VAFSC to get to feature parity with the current Forms Library.
- Combined these two requests into the [VAFSC Feature To Do List Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2275180551/WIP+VAFSC+Feature+To+Do+List).

## Considerations
- In the short term, this page will help Matt understand the remaining work to be done on the VAFSC, and the approximate time frame to do that work before it can be fully used by app teams, as he engages in discussions about the future of the Spike teams.
- This page would also be the basis for a handoff discussion with the Design System Team (if a handoff is needed) to help them understand what the completion path for the package looks like. 

## Acceptance Criteria
- [x] A [VAFSC Feature To Do List](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2275180551/WIP+VAFSC+Feature+To+Do+List) has been created in Confluence.
- [x] The page has been reviewed by the following FLT members:
    - [x] Anish
    - [x] BJ
    - [x] Brittany
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Lauryl
    - [x] Micah
    - [x] Nick
- [x] FLT member feedback has been addressed.
- [x] Review 7/29/22 PO Sync feedback updates with Matt.
