### ISSUE TITLE
Upgrade React Router v5 to v6

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#467]
## Description 
Originally FLT was working on updating react router v3 to v5 in ticket #287. After a meeting with the release tools team, we realized that version 5 of react router already exists alongside v3 in vets-website. The upgrade from v5 to v6 is much simpler and aligns more closely with our Q3 objective of getting VAFSC into vets-website for use in pilot projects and an accessibility audit. 

Additionally, with app teams eventually needing to migrate their applications from the old forms library to VAFSC, the original migration work from react router v3 to v5 is a step that doesn't provide value, as migration to VAFSC entails a full rewrite of application structure anyway. Because of this, FLT is tabling the work originally scoped in #287, and moving ahead with work to upgrade react router v5 to v6. 

## Considerations
- There's a node package that adapts v5 to v6 so they use the same history object.
- Some applications in vets-website already use v5, these will require some minor refactors to ensure they are working properly
- [React Router V5 -> V6](https://reactrouter.com/docs/en/v6/upgrading/v5)
- [react-router-dom-v5-compat](https://github.com/remix-run/react-router/discussions/8753)

## Tasks
- [ ] upgrade the react-router-dom dependency to v6
- [ ] refactor any necessary files
- [ ] ensure tests pass

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into vets-website

**Comment by bjmccotter7192** [comment]
Here is the Draft PR for this change, I would like to get some eyes on this to enhance the wording:
[Draft PR 21718 - React Router V5 -> V6 in vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/21718)

**Comment by bjmccotter7192** [comment]
Merged main and got Draft converted to real PR.

**Comment by taylorkaren** [comment]
Tentatively planning to merge the PR for this ticket on Monday, 7/25/22.
