### ISSUE TITLE
Remove BrowserRouter from FormRouter Component

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#478]
## Description
To prepare VAFSC for use in vets-website, we need to move `BrowserRouter` out of `FormRouter`. 

## Considerations
- Could move it into the index.js file for burials example
- Related to #258 and #467

## Tasks
- [ ] Move `BrowserRouter` out of `FormRouter`
- [ ] Make sure burials form still works as expected
- [ ] Fix any unit tests that break

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
