### ISSUE TITLE
(8/9/22) Focused Walkthrough Session 2: Adam Whitlock

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#496]
## Task Description
Schedule and participate in a second focused walkthrough session with Adam Whitlock about using the VAFSC for phone number fields, how to detect when a field's value changes, and anything else we want to chat about!

## Considerations
- Record the call
- Take notes on the Confluence page set up for this session: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2297692175/Focused+Walkthrough+Session+2+Adam+Whitlock+and+Sharon+Kasimow

## Acceptance Criteria
- [x] Walkthrough session has been completed
- [x] Notes from the session are documented on the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2297692175/Focused+Walkthrough+Session+2+Adam+Whitlock+and+Sharon+Kasimow)
- [x] A link to the session recording is included on the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2297692175/Focused+Walkthrough+Session+2+Adam+Whitlock+and+Sharon+Kasimow)
- [x] FLT members have reviewed the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2297692175/Focused+Walkthrough+Session+2+Adam+Whitlock+and+Sharon+Kasimow) and added notes, takeaways, and next steps:
    - [x] Anish
    - [x] BJ
    - [x] Brittany
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Lauryl
    - [x] Micah
    - [x] Nick
