### ISSUE TITLE
Write a semantic versioning working agreement document

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#501]
## Task Description
From the 8/1/22 standup conversation: Write a semantic versioning working agreement document that defines what is a "baby" fix, minor fix, major fix, feature, etc. so that we have guidelines for what prefix to use on commits and  semantic versioning handles version numbers the way we want it to.

## Considerations
- The official documentation for how NPM recommends on how to do this: https://docs.npmjs.com/about-semantic-versioning (thank you, Anish!)
- Is there documentation for the VA overall that we could reference for this?
    - If not, we should put together some guidance for our repo.
- Have a mob session to figure out what we want to do (what types of feature and fixes will we be working on). 

## Acceptance Criteria
- [x] Semantic versioning guidelines that include the details noted in the Task Description have been documented [Confluence document here](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2308866093/VAFSC+Releases+will+follow+Semantic+Release+Patterns)
- [x] Guidelines documentation has been reviewed by FLT members:
    - [x] Anish
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren 
    - [x] Micah
    - [x] Nick
- [ ] All feedback has been addressed.
- [ ] Guidelines documentation is linked to from the following pages:
    - [ ] [VA Forms System+Core (VAFSC) Work Stream](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2280161283/Draft+VA+Forms+System+Core+VAFSC+Work+Stream)
    - [ ] [Transition Plan Document](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2264695677/Draft+Transition+Plan+Document)

**Comment by obliviga** [comment]
Here's the official documentation for how NPM recommends on how to do this: https://docs.npmjs.com/about-semantic-versioning

Might help us decide how we want to implement this for VAFSC.

**Comment by micahchiang** [comment]
Engineering decision document - https://vfs.atlassian.net/wiki/spaces/FLT/pages/2308866093/VAFSC+Releases+will+follow+Semantic+Release+Patterns
