### ISSUE TITLE
(8/15/22) Focused Walkthrough Session: Robin Garrison

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#540]
## Task Description
Schedule and participate in walkthrough session with Robin Garrison about feedback on the VAFSC:
- What you think will work well (or not so well)
- Gaps we need to fill in to make it really usable for building the variety of forms on va.gov
- Pain points with the current system that would be critical to address.

## Considerations
- Record the call
- Take notes on the Confluence page set up for this session: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2317451265/Focused+Walkthrough+Session+Robin+Garrison

## Acceptance Criteria
- [x] Walkthrough session has been completed
- [x] Notes from the session are documented on the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2317451265/Focused+Walkthrough+Session+Robin+Garrison)
- [x] A link to the session recording is included on the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2317451265/Focused+Walkthrough+Session+Robin+Garrison)
- [x] FLT members have reviewed the [session page in Confluence](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2317451265/Focused+Walkthrough+Session+Robin+Garrison) and added notes, takeaways, and next steps:
    - [x] Anish (watch recording and add notes/takeaways/next steps to the page)
    - [x] BJ
    - [x] Harshil (watch recording and add notes/takeaways/next steps to the page)
    - [x] Karen
    - [x] Kristen
    - [x] Lauren (review some of the recording and add notes/takeaways/next steps to the page)
    - [x] Lauryl
    - [x] Micah
    - [x] Nick (watch recording and add notes/takeaways/next steps to the page)
