### ISSUE TITLE
Initialize data with undefined instead of empty string

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/va-forms-system-core#543]
## Description
When we submit the data we remove the fields which are unnecessary or empty input fields which are optional. Similar to vets website we want to remove all unnecessary fields from the object before we submit to vets-api.

As part of this story, we want to either write a logic to remove the empty strings or initialize data without empty strings.

## Tasks
- [ ] Initialize initial object with undefined instead of empty strings

## Acceptance Criteria
- [ ] Tasks have been completed
- [ ] Pull request has been merged into main
