### ISSUE TITLE
Update the VA Forms System Core Technical Design Document

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#558]
## Task Description
- Update the [VA Forms System Core Technical Design Document](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2025029667/VA+Forms+System+Core+Technical+Design+Document+Working+document) to reflect the state of the VA Forms System Core package as of September, 2022.
- Would be really beneficial to have a section on the Review Page in this document. What developers would need to do to build their own review page: talk about how dynamic review page is designed and what to do to build it that way. go into the code and provide links.
    - Lauren added some information as of 8/26/22; what more should we add to explain how adding Save in Progress functionality would affect the Review Page?
    - Micah unsure how Save in Progress would affect the review page; maybe if you fill everything out and come back later to submit?
    - Lauren: Thinking about pages needing to be indexed somehow even if you are not going through the pages when you come back to the form. No config to associated data to each page.
- All engineers should review and add/update beneficial information in this document.

## Acceptance Criteria
- [x] The [VA Forms System Core Technical Design Document](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2025029667/VA+Forms+System+Core+Technical+Design+Document+Working+document) has been updated to reflect the state of the VA Forms System Core package as of September, 2022.
- [x] FLT members have reviewed the [VA Forms System Core Technical Design Document](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2025029667/VA+Forms+System+Core+Technical+Design+Document+Working+document) and provided feedback:
    - [x] Anish
    - [x] BJ
    - [x] Harshil 
    - [x] Karen
    - [x] Lauren
    - [ ] ~~Nick~~ - Did not complete. 
- [x] All feedback has been addressed.
- [x] Update the Transition Plan and VAFSC Work Stream pages (Karen)

**Comment by bjmccotter7192** [comment]
I did a quick over look and it seems good to me!
