### ISSUE TITLE
Forms Library documentation update process on the VA Platform Documentation Website

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#559]
## Task Description
- Define and document the process for handling documentation update requests (add, remove, modify) to the Forms Library help documentation located in the [VA Forms Library Overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview) section of the VA Platform Documentation website.
- Make this a lightweight process for how app team engineers can contribute to this documentation. 
- Stand up content on the main help page with directions to submit request?
    - If you see something missing, write it up in markdown on a ticket and submit the ticket?
    - Link checking is important when working with submitted content.
    - Could model this after the "If you don’t see what you are looking for..." text on https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-tos.
    - Stand up a GitHub template for doc request submission?

## Considerations
- How do people notify the team supporting the Forms Library that they have a documentation request?
- What does the team supporting the Forms Library do when that request is received?
- Are the team members supporting the Forms Library the only people who should make the documentation updates, or should app team members be encouraged to directly update the help docs?
- Think about the documentation Robin Garrison recently submitted for the subtask pattern (ticket #544). It isn’t ideal for our engineers to have to add that, but there doesn’t seem like a way to allow non-platform users access to add docs themselves.

## Acceptance Criteria
- [ ] The process for handling documentation update requests (add, remove, modify) to the Forms Library help documentation located in the [VA Forms Library Overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview) section of the VA Platform Documentation website is documented on a Confluence page in the [Forms Library Work Stream](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2279768116/Forms+Library+Work+Stream) section of the FLT Confluence space.
- [ ] FLT members have reviewed the [Confluence page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2356707427/Forms+Library+documentation+update+process) and provided feedback:
    - [ ] BJ
    - [x] Harshil 
    - [x] Karen
    - [x] Lauren
- [ ] All feedback has been addressed.
- [ ] Reference to this page has been added to the relevant transition documents (Karen).

**Comment by taylorkaren** [comment]
Per discussion in the 9/9/22 standup call, we are going with the following plan:
- Update the [existing documentation request form used by the Design System Team](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=&labels=vsp-design-system-team&template=2_documentation_request_form.yml) to include Forms Library selections for documentation requests. See this PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1192/files.
- Update text on two pages on the Platform documentation site to reference that form (these are the links to the Staging site):
    - https://vfs.atlassian.net/wiki/spaces/pilot/pages/2085355587/VA+Forms+Library+Overview
    - https://vfs.atlassian.net/wiki/spaces/pilot/pages/2162622465/VA+Forms+Library+-+How+Tos
- These updated pages should be deployed to production as part of the daily deploy on Monday, 9/12. When that is complete, the updated text will appear on these live site pages:
    - https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview
    - https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-tos
- And we will archive the page that Harshil created.
