### ISSUE TITLE
UXPin prototype feedback for Kristen

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#583]
## Task Description
Use this ticket to add feedback items found when reviewing the updated UXPin prototypes that Kristen is developing via work on ticket #172. Add rows to the table in the Feedback section with your insights. Notes might include things about:
- Any broken interactivity (e.g. "I clicked here and expected it to go to this page/jump to this anchor, but it did not"). Please provide the page number and steps to reproduce the bug (click the site map in the upper left corner to expand it) in your bug report.
- Any typos, inconsistent capitalization, or weird/unexpected/inconsistent spacing. 
- Any discrepancies between the UXPin prototype and the demo form that aren't listed in https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/584. 
- Any other suggestions or issues that you want the team to be aware of.

## Prototype Links
- [Final Demo - Mobile View](https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/157175401?mode=cvhd )
- [Final Demo - Desktop View](https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/157175415?mode=cvhd )

## Feedback - Mobile Prototype
| Name | UXPin Page URL | Comment | Done? | 
| --------------- | --------------- | --------------- | --------------- |
| Lauryl | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152776006/simulate/sitemap?mode=cvhd | maybe have a hint on this page as well to click on the plot or interment button | Y |
| Lauryl | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745594/simulate/sitemap?mode=cvhd - but relevant for both mobile and desktop | We should add a hint to this page for users to select "Yes", so they can see the interaction, like what you have hinted on this [page](https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152776005/simulate/sitemap?mode=cvhd) |  Y |
| Lauryl | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152776126/simulate/sitemap?mode=cvhd | As you noted when we walked through, this page shows that random gray bar on the text fields. Not a huge deal, but certainly weird that it only shows up there! KT: Anish has reported the same issue (below) for the desktop version.| Y |
| Lauryl | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745589/simulate/sitemap?mode=cvhd | Should VA File number also be marked as a required field? KT: Production form looks like this: ![Screen Shot 2022-09-06 at 8.00.31 AM.png](https://images.zenhubusercontent.com/6177f86fa75d95db28de0126/eca1357b-27d2-48d7-bec2-0a566741d2ed)| Y |
| Karen | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745597/simulate/sitemap?mode=cvhd | This question should be marked as a required field. | Y |
| Karen | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152746150/simulate/sitemap?mode=cvhd | Can we show Burial allowance as checked here? Then it makes more sense that the next page shows “Step 7 of 9.” | Y |
| Karen | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152746971/simulate/sitemap?mode=cvhd | Would be helpful to have a hint here highlighting that this page is shown because Burial allowance was checked on the previous page, which adds a page to the form flow. | Y |
| Karen | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745599/simulate/sitemap?mode=cvhd | Would be helpful to have a hint at the top of this page to scroll down to the Deceased Veteran information section to edit the Social Security Number. | Y |
| Karen | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745599/simulate/sitemap?mode=cvhd | In the Benefits selection section, “Transportation amount incured” should be “Transportation amount incurred” | Y |
| Karen | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745591/simulate/sitemap?mode=cvhd | Would be helpful to have a hint here to update SSN to 034-82-2016 and choose Save and Continue. | Y |
| Karen | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745594/simulate/sitemap?mode=cvhd | Would be helpful to have a hint here to select Yes, enter required info, and choose Save and Continue. | Y |
| Karen | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/154697070/simulate/sitemap?mode=cvhd | Would be helpful to have a hint here to enter required information and choose Save and Continue.  | Y |
| BJ | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745588/simulate/sitemap?mode=cvhd | ~~Relationship to the deceased Veteran is required but doesn't allow me to choose an option~~ Don't do, we will address this with the disclaimer text on Step 1 | N/A |
| BJ | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152746145/simulate/sitemap?mode=cvhd | ~~Veteran's death occurred is required but doesn't allow me to select a choice~~ Don't do, we will address this with the disclaimer text on Step 1 | N/A |
| BJ | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745597/simulate/sitemap?mode=cvhd | ~~Veteran serve under any other name should be required and is not, and also can't select anything.~~ Don't do, we will address this with the disclaimer text on Step 1 | N/A |
| BJ | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152746150/simulate/sitemap?mode=cvhd | ~~Required fields but can't select any options~~ Don't do, we will address this with the disclaimer text on Step 1 | N/A |
| BJ | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152746971/simulate/sitemap?mode=cvhd | ~~No radio buttons are allowed to be selected for either required field~~ Don't do, we will address this with the disclaimer text on Step 1 | N/A |
| BJ | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152776126/simulate/sitemap?mode=cvhd | Street Address should be required | Y |
| BJ | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/154697070/simulate/sitemap?mode=cvhd | ~~Required radio buttons are still not allowing me to select them~~ Don't do, we will address this with the disclaimer text on Step 1 | N/A |
| BJ | https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/154776036/simulate/sitemap?mode=cvhd | ~~Required policy checkbox doesn't allow me to select before submitting my application.~~ Don't do, we will address this with the disclaimer text on Step 1 | N/A |

## Feedback - Desktop Prototype
| Name | UXPin Page URL | Comment | Done? | 
| --------------- | --------------- | --------------- | --------------- |
| Lauryl | n/a | all the comments I had above re mobile design also apply to the desktop version | Y |
| Karen | https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/152785241/simulate/sitemap?mode=cvhd | As in the mobile prototype, this question should be marked as a required field. | Y |
| Karen | https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/152793876/simulate/no-panels?mode=cvhd | As in the mobile prototype, can we show Burial allowance as checked here? Then it makes more sense that the next page shows “Step 7 of 9.” | Y |
| Karen | https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/153151613/simulate/no-panels?mode=cvhd | As in the mobile prototype, would be helpful to have a hint here highlighting that this page is shown because Burial allowance was checked on the previous page, which adds a page to the form flow. | Y |
| Karen | https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/152785246/simulate/no-panels?mode=cvhd | As in the mobile version, would be helpful to have a hint at the top of this page to scroll down to the Deceased Veteran information section to edit the Social Security Number. | Y |
| Karen | https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/152785238/simulate/no-panels?mode=cvhd | As in the mobile version, it would be helpful to have a hint here to update SSN to 034-82-2016 and choose Save and Continue. | Y |
| Karen | https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/152785244/simulate/no-panels?mode=cvhd | As in the mobile version, it would be helpful to have a hint here to select Yes, enter required info, and choose Save and Continue. | Y |
| Karen | https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/153145984/simulate/no-panels?mode=cvhd | As in the mobile version, would be helpful to have a hint here to enter required information and choose Save and Continue. | Y |
| BJ | N/A | ~~Same issues as the Mobile demo above~~ Don't do, we will address this with the disclaimer text on Step 1 | N/A |

## Feedback - Desktop and Mobile Prototypes
| Name | UXPin Page URL | Comment | Done? | 
| --------------- | --------------- | --------------- | --------------- |
| Karen | All Review page instances | Social Security field label should be Social Security number. | Y |
| Lauryl | Step 1 - mobile + desktop | worth adding a disclaimer/language that no inputs needed, and the steps of the form are just to give context to the review page? KT: Yes, let's do this. That will resolve a number of BJ's comments. Also note in this text that required field validation is not enabled and check boxes and radio buttons are not selectable when moving through the form pages. | Added to landing page |
| BJ | BOTH | ~~Just seems like a lot (maybe all) radio/checkbox fields should have a value by default or should be allowed to be entered (IF required)~~ Don't do, we will address this with the disclaimer text on Step 1 | N/A |
| Anish | https://preview.uxpin.com/b25cc79d1fe3c036b5b560a17c016adb01a738bc#/pages/152785781/simulate/no-panels?mode=cvhd | The input fields have vertical scroll bars. | Y |
| Micah | Service History Page | Branch of service should be updated to a dropdown menu with Air Force, Army, Coast Guard, Marine Corps, Navy, Space Force | Y |

## Acceptance Criteria
- [x] The prototypes have been reviewed by the following FLT members and findings have been documented in the Feedback section of this ticket:
    - [x] Anish
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauryl
    - [x] Lauren
    - [x] Micah
    - [x] Nick
- [x] FLT member feedback has been addressed by Kristen
- [x] Updated links to the UXPins files are noted on this ticket.
- [x] Update links to the UXPin files on the relevant transition pages in Confluence (Karen - Transition Plan, VAFSC Work Stream, and Feature To Do List pages)

**Comment by taylorkaren** [comment]
@bjmccotter7192: Thank you for your timely review! Your comments reminded me that we need to document somewhere a decision that Lauryl, Kristen and I made about going through the form pages - in the interest of time, we did not put required field validation in, and we did not enable the ability to select check boxes and radio buttons. This should be noted in a hint on the first screen of each prototype - I will add this to the comments list.

**Comment by bjmccotter7192** [comment]
> @bjmccotter7192: Thank you for your timely review! Your comments reminded me that we need to document somewhere a decision that Lauryl, Kristen and I made about going through the form pages - in the interest of time, we did not put required field validation in, and we did not enable the ability to select check boxes and radio buttons. This should be noted in a hint on the first screen of each prototype - I will add this to the comments list. 

Ahhh makes sense sorry probably could have found that through the slack threads.

**Comment by obliviga** [comment]
Besides some minor cosmetic issues, I don't have anything else to add that already hasn't been added. Nice job @kristen101606 !

**Comment by kristen101606** [comment]
@taylorkaren All feedback has been addressed. I'm moving this ticket to Ready for Review. Once you confirm that it meets the acceptance criteria, you can close it or ask me to do so. : )

**Comment by taylorkaren** [comment]
Re-opening this ticket to address issues on one page.
 
Page: https://preview.uxpin.com/f314b92e80b6a3610cfc8e4b5c035f37a11197f9#/pages/152745611/simulate/sitemap?mode=cvhd

Issues:
1. Deceased Veteran information section
Social Security —> Social Security number

2. Military service history section
Service Number number —> Service Number

**Comment by kristen101606** [comment]
@taylorkaren Good catches. Changes are complete! The production form uses "Service number" (sentence case), so I've used that. Let me know if you'd like me to change it to title case.
