### ISSUE TITLE
[Routing] Chapter Component

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#599]
## Description
VAFSC has a [chapter component](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/666b77725f4b93cd991713a6f0bd9002bb147c98/src/routing/Chapter.tsx#L10) that isn't currently in use. Originally it was intended to render child routes through the use of a react-router v5 `Switch` component, but we ran into compatibility issues when we upgraded VAFSC to react router v6. 

The chapter component should be resurrected and exposed as an optional component engineers can use to semantically group pages together. This would impact how information is presented on the review page. 

## Considerations
- [Current chapter component](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/666b77725f4b93cd991713a6f0bd9002bb147c98/src/routing/Chapter.tsx#L10)
- Should use a router v6 `Routes` component
- FormRouter currently relies on a [PageContextProvider](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/de54765232de4d67f089d801d87e7936a3c71237/src/form-data/PageContext.tsx#L15) to manage current route. Adding a chapter component would impact this, as pages grouped into a chapter would share a part of the url. 

## Tasks
- [ ] Rewrite chapter component so it can manage child routes
- [ ] Write unit tests for chapter component
- [ ] Ensure chapter data is displayed sensibly on the review page

## Acceptance Criteria
- [ ] Tasks have been complete
- [ ] PR has been merged into main
