### ISSUE TITLE
Update the Feature To Do List page

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#603]
## Task Description
- Update the [VAFSC Feature To Do List](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2275180551/VAFSC+Feature+To+Do+List) to reflect the state of work on the VA Forms System Core package as of September, 2022.
- Micah and BJ to review the page, add any work currently missing from the list, and update or enter LOE estimates where applicable.
- Karen will then review and update the the timeline narratives and roadmap.

## Acceptance Criteria
- [x] The [VAFSC Feature To Do List](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2275180551/VAFSC+Feature+To+Do+List) document has been updated to reflect the state of work on the VA Forms System Core package as of September, 2022 as described above.
- [x] Update the Transition Plan and VAFSC Work Stream pages (Karen)
- [x] Take the In progress indicator and WIP text off the page. (Karen)

**Comment by taylorkaren** [comment]
9/2/22: Micah completed his review of this page.

**Comment by micahchiang** [comment]
@taylorkaren - I just remembered something that needs to be added. I didn't see an entry in the table for file upload work. I'll add a comment now.

**Comment by taylorkaren** [comment]
@bjmccotter7192: I've taken a pass through this page to incorporate the LOEs and notes you added yesterday. Could you please give it a sanity check proof read? I'll give it another read after your read, just to make sure we're all good.

Thank you!

**Comment by bjmccotter7192** [comment]
@taylorkaren Looks good to me
