### ISSUE TITLE
Consolidate SiP config into a single object

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#86]
## Description
[Original DST ticket](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/14690) (Opened 10/9/2020)

The configuration for save in progress (SiP) is scattered among a handful of `formConfig` options:
- savedFormMessages
- prefillEnabled (technically available independently of SiP)
- customText

This makes it difficult to understand when these configuration options should be used and when they can be ignored.
These configuration options should be consolidated into a single config object for clarity.

## Considerations
- How would current forms be affected by this refactoring? 
- Unit tests may need to be updated.
- Add Tasks and Acceptance Criteria as needed to account for any additional work to be done for these considerations.

## Tasks 
- [ ] Determine all the `formConfig` options used for SiP
- [ ] Group them into a single `saveInProgress` object
- [ ] Update the components and functions which use these options
- [ ] Update any documentation around SiP

## Acceptance Criteria
- [ ] All SiP options are in a single place in the `formConfig`
- [ ] Components and functions which use these options are updated to use the refactored single SiP config object 
- [ ] SiP documentation is updated

**Comment by taylorkaren** [comment]
Closing this ticket with no action taken. This is not a critical issue in the current Forms Library and this function will be rebuilt as part of the new VA Forms System Core application.
